### ISSUE TITLE
Query Whitelisting / Persisted Queries

### ISSUE THREAD

**Issue by StevenLangbroek** [markhuot/craftql#10]
So, beside CRUD permissions, another angle would be to allow clients to extract their queries and submit them to an endpoint, basically disallowing any other queries. The problem this prevents is people using your GraphQL API to basically crawl your content. I'm gathering examples + documentation on the matter, curious what your thoughts are.

**Comment by StevenLangbroek** [comment]
- [ExpressJS middleware](https://github.com/restorando/graphql-query-whitelist)
- [Talk about best practices](https://www.youtube.com/watch?v=1Fg_QtzI7SU&t=6s)
- [Article by Apollo](https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5)

**Comment by markhuot** [comment]
This is definitely something I'd like to support down the road. I think it's a bit too early to add it in today as the schema is still a bit in flux (directive support, mutation work, etc…). I'm also curious to see if persisted queries eventually make their way in to the GraphQL spec.

Long story short, I'd like to support it and see it on the roadmap but I'm not ready to commit to it today unless you have a compelling use case for it on a current project.

I updated the [roadmap](https://github.com/markhuot/craftql/blob/master/README.md#roadmap) with a reference to this issue. I'm going to close this, for now. Feel free to re-open if you have an immediate need for this.

**Comment by mashema** [comment]
Hi Mark, wath is the timeframe, for implementing Persisted Queries

**Comment by mashema** [comment]
Apollo approche
Automatic Persisted Queries (APQ)
https://www.apollographql.com/docs/references/engine-proxy.html#automatic-persisted-queries
