### ISSUE TITLE
Query Plugin Global Data

### ISSUE THREAD

**Issue by bschulz87** [markhuot/craftql#102]
I'd like to know if it's possible to get global data from plugins. For example 'seomatic.meta.seoTitle' from the nystudio107/craft-seomatic plugin. I tried to query 'seomatic' like this but only get an error: Cannot query field \"seomatic\" on type \"GlobalsSet\".

`{
  globals {
    seomatic {
      meta
    }
  }
}`

**Comment by markhuot** [comment]
This isn't possible today. I'm going to close this ticket. The 2.x branch is progressing and will change how plugins interact with CraftQL.
