### ISSUE TITLE
ability to query assets directly?

### ISSUE THREAD

**Issue by davefischoff** [markhuot/craftql#104]
I see that you've implemented the ability to directly query entries and categories, but is there any way to directly query assets? I'd like to use craftql to get all assets that have a field with a specific value.

**Comment by markhuot** [comment]
Not yet! But I like it. I'll work on adding this in.

**Comment by markhuot** [comment]
`dev-master` now contains the ability to query assets outside of any entries. You'll use it like this,

```graphql
{
  assets(filename:"foo") {
    id
    title
    filename
    url
    ...on DefaultVolume {
      # fields attached to the volume
    }
  }
}

**Comment by davefischoff** [comment]
Hi Mark,

That's great, thanks for the update!

Take care,
Dave

**Comment by davefischoff** [comment]
Hi Mark,

As a future feature request, if you could add the ability to use custom
fields when querying assets, that'd be great!

Thanks,
Dave

**Comment by markhuot** [comment]
Custom field querying on the top level `assets` field is now available on the `dev-master` branch.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
