### ISSUE TITLE
schema does not provide id field for mutation on matrix

### ISSUE THREAD

**Issue by cpecher-wcd** [markhuot/craftql#105]
Trying to update values in a matrix, the schema lists a field 'foo' instead of 'id' for the input. Actually there is no field named 'foo' specified in the matrix(only 'key' and 'text').
<img width="516" alt="craft_mutation_matrix" src="https://user-images.githubusercontent.com/32677247/41007411-0e583f36-6926-11e8-8d2c-7210e23e2347.png">

**Comment by markhuot** [comment]
Ah, I see, `foo` is definitely some debugging code left in there. I'll get it removed.

As for `id`, that's interesting. I actually don't think it's possible in the current version of Craft to pass in the `id` of the matrix block to upset a single block… Instead, when Craft accepts a matrix field it expects all of the matrix blocks to be passed in together. So, you'd need to pass in something like this,

```graphql
mutation {
  upsertTextsGlobals (textMatrix: [
    {block: {key: "somekey", text: "new text"}
    {block: {key: "second key", text: "second text"}
    {block: {key: "third key", text: "third text"}
  ]) {
      ...
  }
}
```

**Comment by cpecher-wcd** [comment]
I am afraid that doesn't really work for us. If we don't provide an `id` a new matrix entry is created. Since we have multiple languages/sites the data in all other languages is replaced as well. Is it possible to define a siteid/sitename for a mutation? We tried to use different paths for the endpoint (/en/api, /de/api), but it doesn't help in that case.

**Comment by cpecher-wcd** [comment]
Tested it and it works great. Also updating values of different sites/languages was possible using their specific paths for the api endpoint. Thanks for your work on the plugin!

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
