### ISSUE TITLE
Allow for a URL or absolute URL for api endpoint

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#106]
Currently you support relative URLs for the api endpoint, but would like to use an absolute URL. Our frontend is a react app with a different URL, which we provide so that craft fields with URLs/links provide the correct full url (and not the URL to where Craft is hosted). If we add the site url, then craftql will use that as the host when constructing the api endpoint URL, and everything falls apart.

**Comment by markhuot** [comment]
I'm not sure this is the right way to go. I'm worried that overriding this in CraftQL for images will get you part of the way there but you'll keep coming up against other parts of Craft that are expecting one domain but outputting another. Instead, I think you can work around this in your `config/general.php` logic. I may suggest something along the lines of,

```php
'siteUrl' => @$_SERVER['REQUEST_URI'] == '/api' ? 'http://foo.bar' : null
```

This way absolute links, images, etc… should all use the correct domain?

**Comment by askogrand** [comment]
Yeah, I can see the worry about it causing more problems down the line. I think this is a clever work around.
