### ISSUE TITLE
possibility to pass siteId/site argument for mutations

### ISSUE THREAD

**Issue by cpecher-wcd** [markhuot/craftql#107]
queries already support this functionality. would be great to see it for mutations too. current workaround is to use the site specific path for the endpoint.

**Comment by markhuot** [comment]
This is implemented on `dev-master`. You can pass the `siteId:` argument and it will both query for entries from that site as well as set the `siteId` correctly for new content.

For example this will find entry 123 from site 2 and set the title to `foo bar`.

```graphql
mutation {
  upsertEntryType(id:123, siteId:2, title:"foo bar") {
    id
  }
}
```

And this should create a new entry in site 2 with the title `hello world`.

```graphql
mutation {
  upsertEntryType(siteId:123, title:"hello world") {
    id
  }
}
```

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
