### ISSUE TITLE
access control Tokens may probably need tightening

### ISSUE THREAD

**Issue by narration-sd** [markhuot/craftql#108]
Hi Mark,

I've been assuring access control in something substantially using CraftQL, and run into two things.

- Token::forUser() looks like it was just scaffolded on Token::admin(), not completed, and so it would give total admin Schema permissions for any user(!).'

- as well, Token::findId() will revert to Token::forUser if it's called with a falsey Id -- which is just a little bit unsafe if one is using the Token::tableName etc. to query up a Token (id) on a name that might be wrong, no?

The second point is a design one, am sure you may feel, but perhaps this evident danger might suggest making user-based token discovery just entirely separate. 

I appreciate the convenience factor you were going for, but hoping you might think about this.

CraftQL itself is really quite fun, and quite a nice job; would like you to know it's appreciated.. 

Oh, one more point then, not a million miles away from this discussion.  It's that in the Token creation UX, you're encouraged to use a link to try out your newly specified Token; however, the screen from this seems to just stop with 'Loading...'.  I haven't debugged it to see why.

**Comment by markhuot** [comment]
Hi @narration-sd, a few responses for you,

> Token::forUser() looks like it was just scaffolded on Token::admin(), not completed, and so it would give total admin Schema permissions for any user(!).'

This is restructured in the `dev-user-tokens` branch. That will merge to master as some point in the not too distant future. With that branch the Craft user permissions were updated to support CraftQL so you can now permission users  as well as tokens. This allows you to provide users access to CraftQL without providing them full admin access in, as you found.

> Token::findId() will revert to Token::forUser if it's called with a falsey Id -- which is just a little bit unsafe if one is using the Token::tableName etc. to query up a Token (id) on a name that might be wrong, no?

On the `dev-user-tokens` branch I've introduced the "anonymous" role which is what an invalid or missing bearer token returns. Anonymous users only have access to the `{ helloWorld }` field to validate that the system is working. The falsey ID check has been removed.

> It's that in the Token creation UX, you're encouraged to use a link to try out your newly specified Token; however, the screen from this seems to just stop with 'Loading...'. I haven't debugged it to see why.

This is fixed on the `dev-master` branch and will make it in to a stable release within the next few weeks.

I believe this addresses all of your concerns. If you agree let's close this ticket. You can track the `dev-user-tokens` and permissions updates over in #89.

**Comment by narration-sd** [comment]
Hi Mark, 

That all sounds thoughtful and good, appreciated. Good confidence for futures also.

I did scope some of the alternate branches, but mainly to see they were not ready just to pull down for use, and so missed where you'd gone after these things.

I'll close, and there's no rush from this end -- I've taken care of here everything I need to for now.

Thanks,
Clive

**Comment by narration-sd** [comment]
a p.s. just noticed what you said about the dev-master version -- for some reason I've been using the 1.0@beta release, so will switch over, as dev-master is what I use for Craft and other solid parts.

Thanks again, Mark

**Comment by narration-sd** [comment]
Hmm also, and thanks for coming back on this -- I'll dig into it shortly.

I've had a hard fail on first use -- somehow not having apparently any Schemas available. So it's probably an initialization step or argumente that's been added, which I don't yet employ. Or something changed indeed about the getSchema we were discussing -- could be it.

I'm accessing through the service, if that makes any difference -- but let's see; shouldn't be hard to find as you've stood up for the branch.

**Comment by narration-sd** [comment]
Ok, Mark -- have to leave for a while, but I tracked it down so far to area, and found workaround for moment.

- the problem comes in the `$schema->assertValid()` call at line 99 of GraphQLService.php.
- this is actuated only if Craft devMode is on. 
- Turning devMode off, gql queries return to working fine, which shows the Schema is valid for things I use and permitted to the Token.
- I was tracing and ran out of time, but it's one of the later passes of the forEach loop at line 419 of Schema.php, within `assertValid()`,  which fails.
- here is the Exception message trapped, including my prefix, and which shows the same within debug:

> schema creation failed for name: (my tokenname): Could not find possible implementing types for CategoryInterface in schema. Check that schema.types is defined and is an array of all possible types in the schema.

- Now, I'm not permitting Categories in the Token creation, nor using them.
- I checked the properties of the Token retrieved from your id in the database, and that itself shows just the Elements I'd created it to access. 
- this Token works fine, as the created Schema does,  once devMode is off.

Maybe this will give you an idea?

Cheers,
Clive

**Comment by narration-sd** [comment]
...and: I've given this a late evening half hour, just because I suppose of curiosity what you're doing in there, helped by PhpStorm being able to break on Exceptions before they';re taken, and come up with what seems the central issue.

It's that the `CategoryInterface ` type doesn't exist on the `possibleTypesMap`, which seems to include only types I've mentioned in my query or from certain (non-`internalType`?) fields in them:  not very many.

I guess you'll know why it's checking for this in the assertValid in getSchema, or know why it shouldn't, no?

This code area reminds me of how I once determined that I wasn't a mathematician, despite any ability for grades there :)

**Comment by markhuot** [comment]
Thanks for digging deeper on this. The issue was that my code was assuming there was at least one category group set up in the system. If there were no category groups the Interface was still added without any actual category groups implementing the interface, which is a no-no for GraphQL.

The `dev-master` branch fixes this now.

**Comment by narration-sd** [comment]
Thank you, Mark -- that fixes the problem, verified here.

I was interested in your fix, which underlines the logic of your graph depth-search pattern. And such a miss is easy enough to make, as it's negative testing needed to find it, while we tend to privilege thinking about the positive side.

Take care,
Clive

**Comment by markhuot** [comment]
Thanks @narration-sd! I'm going to leave this open until I cut a stable release from `dev-master`.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes a fix for the categories issue. There is still ongoing work with the user tokens mentioned up top.

**Comment by narration-sd** [comment]
Sounds great, Mark. I've been using it via dev-master for the recent months, and no hiccups at all.

I'll have to tell you what I'm up to soon -- at the moment I've inadvertently broken your part by completion refactors/improvements, but it'll be back quite soon. I think you'll be interested. 

And while I'm serving relatively complex element-apis as well, the experience has pretty well convinced me  that GraphQL is quite a coming thing.  Facebook?  Well... :)

**Comment by narration-sd** [comment]
@markhuot ^^

**Comment by markhuot** [comment]
Exciting. Can’t wait to hear what you’re working on. Feel free to email me directly if that’s better. Email address is on my GitHub profile.
