### ISSUE TITLE
Suppport for radio buttons

### ISSUE THREAD

**Issue by Gogoro** [markhuot/craftql#109]
Hello! I'm using this plugin for the first time, and I love it. 

I hit a bit of a wall with the radio buttons. As far as I can see there is no support for it yet? 

I dug in the issues and found #70 and from there found the `src/Listeners` folder which does not include any file for Radio buttons.

Could someone maybe include it? Right now its being shown in the CraftQL editor as a String:

![image](https://user-images.githubusercontent.com/1327105/41586664-a048287a-73ad-11e8-82a0-aab320f3486a.png)

But ofc I get this error:

![image](https://user-images.githubusercontent.com/1327105/41586690-ad4ca44c-73ad-11e8-9f28-1d35113948b8.png)

For now I can do a hack, but support for radio buttons would be much appreciated! 💯💯💯

**Comment by markhuot** [comment]
Ah, sorry about this, support for Radio buttons got dropped somewhere along the march towards a final release. Support for radio buttons is added back in to the `dev-master` branch, for now. I'll leave this open until it makes it in to a stable release.

**Comment by Gogoro** [comment]
@markhuot Thanks for the quick response! 👍 Good luck with the implementation 😄

**Comment by markhuot** [comment]
Just to be clear, this is implemented and ready for you to test/use if you update your composer config to point to `dev-master`. Again, I'll post when this is in a stable release.

**Comment by Gogoro** [comment]
Ah, nice! Thanks @markhuot  🌮 🎉

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
