### ISSUE TITLE
GET & HTTP header support

### ISSUE THREAD

**Issue by rsanchez** [markhuot/craftql#12]
The spec says the HTTP endpoint can be available over GET as well as POST (http://graphql.org/learn/serving-over-http/#get-request). Would you consider allowing GET requests?

Also, I have a need for setting Cache-Control headers (and custom headers as well). It'd be great to have some kind of hook or configuration setting for adding headers.

The ultimate use case for GET and header support is to aid in client-side caching.

**Comment by markhuot** [comment]
Yup, it makes sense to me to offer the endpoint over GET. I may make it a config option though because I, personally, prefer GraphQL over POST.

Re: the headers: how would you want them set? Are you saying that you need to run custom PHP to set a header with each CraftQL response? Or that you'd set them once in a config and all responses would send the same custom headers?

**Comment by rsanchez** [comment]
Maybe the best way to handle this is with a "before response" hook? Then we can add whatever headers or do anything else we want to the response before it goes out.

Or it could be as simple as a config array of headers. I could see wanting to set CORS or CSP headers, for instance.

Or maybe have the option of both? Set headers in config and also have a before response event?

**Comment by markhuot** [comment]
Good idea. The event is a no brainer. I'll get that added, that should work for now.

I'll think more on whether it's worth adding it to the UI. If it's going to be static stuff maybe shoving them in a `config.php` is just as good.

**Comment by markhuot** [comment]
`1.0.0-beta.10` accounts for these comments!

>Also, I have a need for setting Cache-Control headers (and custom headers as well). It'd be great to have some kind of hook or configuration setting for adding headers.

You can Yii's built in event system to adjust the headers programatically. This would have to be done from another plugin though. E.g.,

```php
Event::on(
    \yii\web\Response::class,
    \yii\web\Response::EVENT_AFTER_PREPARE,
    function ($event) use ($headers) {
        $event->sender->getHeaders()->set('X-Foo', 'bar');
    }
);
```

That seemed like a lot of work for just headers, especially in this new Craft 3/Composer world. Spinning up a plugin _just_ to add a custom header… no thanks. So, I also added a setting for `headers` which maps to an array of key/value pairs per header. E.g., in `config/craftql.php`

```php
return [
    'headers' => [
        'X-Foo' => 'Bar',
    ],
];
```

The setting should account for most "static" use cases, and anything more than that would probably need a custom plugin anyway.

> The spec says the HTTP endpoint can be available over GET as well as POST (http://graphql.org/learn/serving-over-http/#get-request). Would you consider allowing GET requests?

Similarly, there's a new setting named `craftql.verbs` that takes an array of verbs CraftQL should respond to. It defaults to `POST` but you could easily add `GET` in there as well. E.g.,

```php
return [
    'verbs' => ['POST', 'GET'],
];

I'm not sure if I'll expose either of these to the UI… not sure if it's necessary. Both are in the latest release though.
