### ISSUE TITLE
Query sites info

### ISSUE THREAD

**Issue by cpecher-wcd** [markhuot/craftql#123]
Is there a way to query all the sites that are available in craft? It would be great to build e.g. a language selector. Interesting fields could be siteId, primary, name, handle, language, hasUrl, baseUrl and sortOrder.

**Comment by markhuot** [comment]
Not yet, but I can get this added in. Good request!

**Comment by markhuot** [comment]
This is implemented on `dev-master` now. You can query them with,

```graphql
{
  sites {
    id
    name
    handle
  }
}
```

**Comment by markhuot** [comment]
Closing this issue. The fix is included in version 1.2.1.
