### ISSUE TITLE
Tag field support

### ISSUE THREAD

**Issue by rsanchez** [markhuot/craftql#13]
Trying to fetch data from a tag field and getting the following error:

```
String cannot represent non scalar value: instance of craft\\elements\\db\\TagQuery
```

Looks like maybe this is still incomplete? https://github.com/markhuot/craftql/blob/54bbc6009f61e02cb54e6d1ac6210fb78cc00d01/src/Fields/TagsBehavior.php#L29

Thanks for your help!

**Comment by markhuot** [comment]
Ah, nope, just need to be uncommented. One sec…

**Comment by markhuot** [comment]
Gah, uncommented it and it's incompatible with a refactoring I did. I'll get this fixed up though.

**Comment by markhuot** [comment]
`1.0.0-beta.9` should fix this
