### ISSUE TITLE
idNot is great, but seems as  yet not to work on children, or accept multiple values successfully

### ISSUE THREAD

**Issue by narration-sd** [markhuot/craftql#132]
This may be less straightforward than at first seems; if so, might land us in the territory of  https://github.com/graphql/graphql-js/issues/640#issuecomment-268386839.

Maybe it is, though. idNot works for a single value, on the top level of a query.

However, if more than one value is attempted to be specified, using commas,
- the query variable builder insists to automatically make multiple idNot fields for them
- only one value is actually used to filter the query; others are ignored

Further, with one valid idNot, applied to nested Structure Entry records,
- a record having this id on level 1 of the structure will be properly stopped
- but as in the screenshot, the same valid id on a deeper level will not be stopped

I couldn't find any syntax to get around either of these, and both are necessary to work for the needed use. If we can solve these, I can work that problem sent in email, it looks.

Thanks,
Clive

![idnot-not-nested](https://user-images.githubusercontent.com/247945/44070490-fa20d34a-9f38-11e8-9fd6-c1334732e88a.png)

**Comment by markhuot** [comment]
The filter/query issue is tough. Do you have a way to implement this in regular Craft `.twig` templates? I'm going to close this because I don't believe this is a CraftQL issue. However, if you can get me a `.twig` implementation I can take a look at how we would do the same in CraftQL.

**Comment by narration-sd** [comment]
Just happens I'm on this issue at the moment of seeing your reply, having tabled it waiting to hear. I'm not solving it for Twig, but I am doing so for element-api.

It's easy enough there to provide a list of ids not to select, and add that into element-api 'criteria'.

It's possible I've missed something about 'filter' capabilities in basic GraphQL, or what might be added to them. 

Thanks for the keyword, and I'll have a fresh look and see where that leads for this particular issue, get back to you here.

**Comment by markhuot** [comment]
Can you provide any sample code using the element-api of how you would implement it? I'd like to get a better sense of what you're looking for to help figure out how we can do it in CraftQL.

**Comment by narration-sd** [comment]
Ok, in looking through this today, I suspect what I'm talking about would pretty clearly be a directive, like your @date. '

That's because what I really want controlled is presentation of a fragment, dependin on the value 
 of  a field of  the  fragment. A directive would  nicely work as well on a non-fragmented field, also, and maybe a form of this could be provided on a common base later, which allowed field or fragment control on a field of the base query. If that's not my need at present, it might be worth thought?

The distinctions past your  @date form seem to be: 
- there's at least one argument, as in the canonical @include
- the argument(s) need to indicate a field of the fragment, and a list of values for it as an array
- the condition would be nice to provide also to make the directive generic -- in this case 'not in' if following Yii2 syntax

Since @include is normally provided, but with a simple boolean argument, a proposal might be:
- @limit(condition: Array), or more clearly, @itemFilter(condition: Array)
- or possibly it could still be @include(), if GraphQL can be polymorphic on argument types
- condition might in due course nicely become a Yii2 where condition, or some of them, for flexibility
- the only condition I need for the problem now, though, is 'not in' with an array list, so maybe a simpler form could be `@limit('fieldname', 'not in', $list)`, where $list is an array of ids, e.g. [ 22, 54, 740 ]
- or even @idNotIn($list), but again this is different from $idNot as it applies to a fragment after the query, as GraphQL goes...

I would use it as something like the following, where $limit is provided in query variables as that Yii2 where condition array, as 
```
fragment recursive2Nav on PagesPage {
  ...navFields
  children @itemFilter($limit) {    # if $limit was a Yii where condition, ['not in', 'id', [ 22, 574 ]]
    ...navFields
    children @itemFilter('id', 'not in', $list) {    # if second of three proposed forms
      ...navFields
    }
  }
}
```
Thanks much, Mark, and a nice weekend to you.
Clive

Here's example code from an element-api as you asked for, illustrating the difference in filtering a query, which GraphQL/CraftQL can do and I use elsewhere, vs. filtering a field or fragment...not my code, originally.

What I've patched in for a reason of today is fixed arrays, but as commented, these would be dynamic from a plugin, and passed automatically as query variables to CraftQL.

```
function _navItem($page)
{
    $out = [
        'title' => $page->title,
        'id' => $page->id,
        'uri' => $page->uri,
        'url' => $page->url,
        'children' => [],
    ];

    if ($page->hasDescendants) {
        foreach ($page->children as $child) {
            if (!in_array($child->id, [ 574, 733 ])) { // $plugin->currentHiddenids()
                array_push($out['children'], _navItem($child));
            }
        }
    }

    return $out;
}

function _getNav()
{
    $pages = Entry::find()
        ->section('pages')
        -> where(['not in','elements.id', [ 346 ]])
        ->level(1)// just the top
        ->all();

    $output = [];

    foreach ($pages as $page) {
        array_push($output, _navItem($page));
    }

    return $output;
}
```

**Comment by markhuot** [comment]
I think I'm following and I think we can actually get you to where you need by just adding arguments to the `children` field. For example,

```graphql
fragment recursive2Nav on PagesPage {
  ...navFields
  children(limit: $limit) {
    ...navFields
    children(idNot: $idNot) {
      ...navFields
    }
  }
}
```

With that you could pass `$limit: 5` or `$idNot: [1,2,3]`.

Would this work?

**Comment by narration-sd** [comment]
Mark, that looks quite good and sounds it would nicely work.

The provisos would be:t
- that for the fragments, the idNot would operate on the returned data from the original query, rather than the query itself
- that a single idNot indeed accepts an array listing the blocking element ids, so that on the query filter level, similar blocking lists can be used

So you see there are two frames of needed appllcation, query filtering, and fields-or-fragments

Will be interested to see just how you implement this -- sounds as if it could be something in the resolver, rather than a directive?  But will wait to see the code changes, having had the wish I'd the extra time just now to become more familiar with GraphQL internals....

Thanks much indeed,
Clive

**Comment by markhuot** [comment]
Sorry, @narration-sd, I'm not understanding your first bullet fully. Why does `idNot` need to operate on the returned data, rather than the original query? I'm not seeing that in your PHP example, above.

**Comment by narration-sd** [comment]
Mark, it is in there. Have a look at the top routine, navItem(), which is sort of like the fragment part of the gql query. There I'm blocking recursion for children which are on the (static, will be dynamic) id  list, This accomplishes that the banned ones don't show.

Both levels are necessary, query filtering and fragments/fields, due to  the old problem of handling hierarchies on rdbs. Craft's Structure elements each return a list of chlidren when present. _navItem() and the nestted fragments of the gql query need to enable (or block) those.

Thus the bullet --- always open to some other idea of arranging the query,  but this is the way I could come up with based on available google for the pattern, so far...

Does this work for you?

**Comment by markhuot** [comment]
I've been thinking about this and I think it makes sense, but I'm not sure I'd recommend taking this approach. GraphQL doesn't support what you're looking to do so anything I implemented would just be a hack on top of the base library. Instead I would recommend keeping your GQL queries as "static" as possible and doing any business logic filtering in your template or application layer (whether it's PHP or Node, like Gatsby).

**Comment by narration-sd** [comment]
Hmm. I was wondering if you'd had a chance to get to this. The  step to winnow children is in there, about line 12 depending on how you count:

```    if (!in_array($child->id, [ 574, 733 ])) { // $plugin->currentHiddenids()```

but that code is unchecked, and I see now false: there's a missing step to _retrieve_ the actual children. And that's key to what I need.

Let's go back to GraphQL, where you may be able to suggest. Here's a simplified view, which I'm trying out in your nifty CraftQL interface:
``` 
fragment navFields on PagesPage {
  title
  id
  children (idNot: $idNot) {
    id
  }
}

fragment recursive2Nav on PagesPage {
  ...navFields
  children (idNot: $idNot) {
    ...navFields
  }
}

query nav($idNot: [Int]) {
  entries(section: pages, level: 1, idNot: $idNot) {
    title
    id
    ...recursive2Nav
  }
}
```

with queryVars:
```
{
  "idNot": [20, 574] 
}
```
Now, I have two problems here:

1. While  idNot accepts an array of ids, it only _acts_ on the first element, 20. Any further, like 574 here, seem to be ignored, though possibly not all there may be in a list, not always. This I think is just a bug, as mentioned before. I verify this using only the base query, without  the recursive part.

1. But the more serious problem is that this full query is rejected, because  the lines for children are unacceptable. I get errors, with message `"Unknown argument \"idNot\" on field \"children\" of type \"PagesPage\".",` for each of them.

This is just the way I could think of to introduce idNot for the children,

I think you will see that since this is hierarchical menu represented by flat page records having child pointers, the top or left-most items need to be restricted to level: 1, Then the children come, and whether they are shown needs, for application reasons, to be subjected to a blocking list.

Can you suggest how to write the query, with or  without the very welcome relative simplification of the fragments for the recursion, where I can apply idNot to the child elements?

Thanks, Mark, and hoping to have got this very real problem onto your  preferred wavelength,
Clive

**Comment by narration-sd** [comment]
Mark, reply element 3 to your last. I wired up that PHP code just as written into an independent endpoint for element-api -- and, it works just as written. 

This may bear on your thinking, The code works because in Fractal's magic, apparently, full  elements are returned when referenced from fields of a query which may itself have been restricted. 

Thus though my top query restricts to level one, entries which are its return's children get all their values, and are not restricted by the criteria of the initial selection. The second part does seem logical, given the first.

And that's the same way CraftQL, thus I presume GraphQL, is acting. Using idNot, even to the extent it's presently working, on the master (pages) query in CraftQL, is not restricting which children can be returned.

Thus in both cases, api or c/gql,, you see I need to be able to restrict which children are returned, according to their ids.

**Comment by narration-sd** [comment]
Above edited for clarity, if you're reading these by mail

**Comment by narration-sd** [comment]
p.s. I suspect the reason idNot works only on the first element of arrays is that it should be 'not in ', rather than 'not', at line 128 of src/Request.php. 

Too late in a long night here to wire up my fork of your source to try the fix,, but hopeful...

I'll probably have to do that to trace where to put the active part of a directive for the main problem here, yet time is fleeting, hence the hour.

**Comment by narration-sd** [comment]
ok, this last turned out to be a little more involved, due to how a Craft helper gets involved.

Pull request is in at #165, which merged ok, looks like. There were failures in the ci, but these seem to have to do with a problem in Mutation, which hasn't been touched by it?

Thinking in any case that conversation here can revert to only the main topic, which appears to summarize now as whether and how to have a related `@idNot: in` directive...

I apologize for mixing these; this occurred because it first seemed they might be related. 

I'm pretty clear now they're not except in use concept, which is why am framing the directive naming as similar --cheers
