### ISSUE TITLE
Better recovery from inconsistent database

### ISSUE THREAD

**Issue by narration-sd** [markhuot/craftql#14]
@markhuot  Mark, I want to first say, this gives every feeling of a fine piece of work, and I think also one possibly quite important to Craft's future.  So another comment will follow, but here I want to deal with what happened when I first brought CraftQL up, yesterday afternoon.

What I got immediately was your fine UI, smoothly handling itself by showing an exception as JSON in the query result column. Ok, great to see this handled by your plugin, but why? It turned out out after some Xdebug tracing that this was coming from a field definition not fully filled in on this test site's database. I'd defined a tag field, but without yet having any tag definitions available for it.

I imagine this kind of thing could be pretty prevalent, actually, and so following what the Bend team know as my predeliction for adaptive design in software, might I suggest:

- not to stop CraftQL in its tracks over such a db inconsistency. In this case I'd think to simply note it on the top level and go on, allowing queries as a first principle.
- the notification on the top level could then have a link, which when clicked draws out the actual inconsistency, so it can be dealt with. How far you go with this, has to be a judgement, if smoothness goes up with pinpointing. A first step might be just to publish the SQL query that fails, with its error.
- this same diagnostic would then be what you put up if/when a GraphQL query actually runs into the problem, so you're easily double-covered with one piece of error code.
- I quite like that you publish errors in JSON, making them easy to pick up at the calling end, as well as quite readable in the UX, so would keep that for all of this.
- not related, but occurs to mention CORS headers for some circumstances?

In any case, you can tell I'm quite liking your work, and the advantages it opens....

**Comment by markhuot** [comment]
`1.0.0-beta.11` should fix this issue. Now, if you have a broken link between a tags field and the tag group the field will not appear in the schema. I'll look in to adding a `Craft::trace` warning at some point, but it's low priority.

**Comment by narration-sd** [comment]
Seems to work -- tested by reinvoking that disconnected Tags field, and also with an Assets field invented with no sources.

If it's a useful story, I'm thinking back to a natural-language interpreter I created for purpose, consulting to Bell Labs, which went worldwide and lasted 18 years, until tech caught up with doing it by accepted methods. It was flexible and informative in the way I tend to suggest about these matters; held those small conversations in addition to understanding English even with international grammars. 

I understand by experience how different software design is these days, but to return to that word mentioned in a separate but related context, trust is a practically earned matter in this world especially. Brilliance is not enough without this rounding into attending the concerns of others, I think, for what it may be worth?

Cheers, Mark, and best fortune.

**Comment by narration-sd** [comment]
p.s. the queries matching the element-api at present work fine, and so much more easily, esp. as those are not transparent to debug -- similar story. So again, thanks for your work....
