### ISSUE TITLE
future approaches for CraftQL

### ISSUE THREAD

**Issue by narration-sd** [markhuot/craftql#15]
Hi again, Mark.  I've been folllowing with some interest your progress on rights and potential payments since we first teased them on Slack, and read yesterday the license you've come up with.

As I'm getting deeper into Vue and what can be done with it, It's clear how much CraftQL can make nicer, and thus enable, for future kinds of Craft constructions. If the future maybe begins pretty much now....

Especially for such a nice piece of work, CraftQL certainly deserves to be paid for given you want this, so I have a suggestion.

You expressed interest in doing as Craft for licensing, and actually this is what I'd like to suggest, and for the same reasons. Commercial operation above a threshold is paid, and at a sensible figure. But for several reasons, there is a free tier, which I've long thought a very good idea. Why?

- Actually, a free tier has great potential to build the actual paid user base. Besides Craft itself, I've seen other plugin developers use this method as well. And from the kinds of tentativity you see in potential new users on Slack, for example, not to say Craft's numbers, the approach certainly seems to be a success.
- Related, if a bit less direct, is the potential of opening Craft more transparently to single page applications, and less committed partial designs. Again, the paid market should grow as developers get comfortable by being able to try the real components -- in a world where trust is significantly a hands-on thing.
- This part may have quite your own degree of interest certainlky, but I've as personally quite respected the Craft team's approach of having generosity and the benefit of the doubt towards community-orientated and so forth sites. The word 'non-profit' doesn't necessarily mean no-budget at all, but for the less large ones, this may well be true. There's always the side aspect here too of increased reach and tendency to use what it's seen others have good results with -- or on follow-ons which have budget because of success.

Just thoughts to consider, then, Mark; and I think we've got the groundwork laid in abilities to be in the plugin store, after the quite wonderful discussion on that.  

Cheers, then, Clive

**Comment by markhuot** [comment]
Thank you for the kinds words Clive. I still don't know much more about the plugin store than you do. I'm certainly keeping my eyes on it though and if it makes sense will get CraftQL on there.
