### ISSUE TITLE
Query arguments only for exact matches?

### ISSUE THREAD

**Issue by carlcs** [markhuot/craftql#154]
Hesitant to ask this because I haven’t done much with GraphQL yet. Is it currently only possible to use query arguments for exact matches? So there’s no way to query, for example, for entries after a given date, or entries with a price field that has a value in a given range?

I found out about the `idNot` argument and certain arguments like `section` take arrays? `search` works for a some use cases, but I would rather not rely on Craft’s search index and it also doesn’t work with things like lesser or greater than.

**Comment by carlcs** [comment]
Thanks @markhuot, that’s good to know. The problem I ran into was with my first attempt to this kind of query where I wanted to filter by a Number field and CraftQL complained about the type.

> Expected type “Int”, found “> 100”

**Comment by markhuot** [comment]
Ah, yea, that's the strong typing of the underlying GraphQL implementation. What field were you trying to do that on? There's definitely some fields that will break like that and it'd be good if we could find an alternative way to query them.

**Comment by carlcs** [comment]
Now that I know that it works with other field types, I can change my field to a Plain Text field.

**Comment by markhuot** [comment]
That'll work in the short term. I'm going to look at adding the something like this though,

```graphql
{
  entries (numberField:1, numberField_Query:">10") {
    #...
  }
}
```

That way we get the strict typing of the number on the default field but provide a "query" field for times when you need the Craft style searching.

**Comment by carlcs** [comment]
That would be a great feature for sure! Could this potentially also allow to pass in more complex query params?

```graphql
{
  entries (
    numberField_Query:">10"
    dateField_Query:"['and', '>= 2018-04-04', '< 2018-05-01']"
    relatedTo_Query:"['and', { sourceElement: 1, field: 'favoriteDrinks' }, { targetElement: 726, field: 'ingredients' }]"
  ) {
    #...
  }
}
```
