### ISSUE TITLE
Types for "entry" as opposed to "entries"

### ISSUE THREAD

**Issue by StevenLangbroek** [markhuot/craftql#16]
Right now fetching a single entry for a "detail page" is a bit verbose (unless I misunderstand something, if so please feel free to correct):

```graphql
query article($slug: String!) {
  article: entries(slug: $slug, limit: 1) {
     body
  }
}
```

This means my components need to map over entries, even though there's always just a single one... I was previously using GraphCMS, and they expose root queries for single types:

```graphql
query article($slug: String!) {
  article: Article(slug: $slug) {
    body
  }
}
```

What do you think is the best approach here?

**Comment by markhuot** [comment]
Ah, but wouldn't you have to `{% set landingPage = craft.entries.section('landingPage').one %}` in Twig any way? I'm worried about polluting the root fields with every section.

All that said, it _used_ to work this way…

https://github.com/markhuot/craftql/blob/9e67f2e3b27559b381e2be78c5defcd4836c8c80/src/Services/SchemaSectionService.php#L148-L152

And with the new Scopes that I've added you could theoretically control how much you want to pollute that root field list… so maybe it makes sense to bring back _in addition to_ the `entries` field.

**Comment by StevenLangbroek** [comment]
what about just a single `entry` type? Only annoying thing is you'd then have to fragment on its type...

```graphql
query article($slug: String!) {
  article: entry(slug: $slug) {
     body
  }
}
```

**Comment by markhuot** [comment]
Hrm, that's no worse than the fragments you'll have to use on the `entries` field though…

I do like the similarity a single `entry` field has to `craft.entries.one` in Craft 3. (I so want to name it `one` but that would just be horribly confusing.)

----

I'm not sure if I'm excited or terrified that https://github.com/APIs-guru/graphql-lodash could let transform it in the query to get back what you're looking for…

```graphql
{
  entries(section:landingPage) @_(nth:0) {
    id
  }
}
```

**Comment by StevenLangbroek** [comment]
Well like I said, I can hack this together easily and without acquiring too much technical debt, but it's so common there should at least be a "non-hacky" answer to this question. And yeah graphql-lodash, while wildly fascinating, would terrify me in our existing codebase (we have over 80 engineers with varying skill-levels, and someone always finds a creative way of breaking things or going completely abusing things we introduce for things they weren't meant for).

**Comment by markhuot** [comment]
Well, that was easy…

![screen shot 2017-09-06 at 11 05 53 am](https://user-images.githubusercontent.com/48975/30119351-693ded92-92f3-11e7-9306-eb29d4c57630.png)

`1.0.0-beta.12` includes the new `entry` field and takes all the same arguments as the `entries` field.

**Comment by StevenLangbroek** [comment]
Dude, stop being so awesome.

**Comment by StevenLangbroek** [comment]
you're making the rest of us look bad.

**Comment by markhuot** [comment]
I blame Craft 3, mostly 😆.
