### ISSUE TITLE
Extending CraftQL with REST resources?

### ISSUE THREAD

**Issue by jgeschwendt** [markhuot/craftql#167]
I have an SSR App setup using React/Apollo and CraftQL. I'm trying to use some of the Google API's to simplify content management without having to add another HTTP client to the App. Is there an easy way to extend the CraftQL API to use an external resource like the following?

https://maps.googleapis.com/maps/api/place/details/json?key=GAPI_KEY&placeid=PLACE_ID

**Comment by markhuot** [comment]
Interesting…! There's no native way to do that _right now_ through the Craft UI. However,

1. GraphQL, recently, has begun to extend to a concept called "schema stitching" where by one GraphQL schema is _merged_ with another. This won't work for this request, though, because the Google Places API does not run GraphQL. If this was possible you would be able to interact with the two APIs like you could if you were to stitch the GitHub API in to CraftQL, e.g.,

```graphql
{
  craft: entries{id}
  gitHub: repository(name: "craftql", owner:"markhuot"){description}
}
```

2. You could do this with a Craft Module, without _too_ much trouble but it would take some PHP. The module would be responsible for adding a new GraphQL field that would, in turn, do the REST request to Google. Something like this,

```php
$placeType = $schema->createObjectType('GMapPlace');
$placeType->addStringField('name');
$placeType->addFloatField('rating');
$placeType->addStringField('icon');

$field = $schema->addField('map')->type($mapType);
$field->addStringArgument('id');
$field->resolve(function ($root, $args) {
  // make request to Google based on a place ID of $args['id']
  // probably something along the lines of this,
  return $guzzle->get('https://maps.googleapis.com...', [
    'placeId'=>$args['id']
  ]);
});
```

Let me know if this makes sense of if there's anything else I can do to help.

**Comment by jgeschwendt** [comment]
Awesome!, I'll give writing a custom Craft Module a try and reach-out if I get stuck.

I've had success using schema stitching in the past. However, for this App the budget is small and and adding infrastructure is not ideal, so extending the CraftQL API makes more sense.
 
For anybody looking for a solution using Schema Stitching with CraftQL it can be done fairly easily with a Node.js server (or in the code below, written in TypeScript, using AWS Lambda). This solution is great for projects that use an architecture with multiple external APIs or Microservices.

```typescript
import { HttpLink } from 'apollo-link-http'
import { 
  introspectSchema,
  makeExecutableSchema, 
  makeRemoteExecutableSchema, 
  mergeSchemas 
} from 'graphql-tools'
import { GraphQLServerLambda } from 'graphql-yoga'
import fetch from 'node-fetch'

import resolvers from './resolvers'
import typeDefs from './schema/schema.graphql'

import pkg from '../package.json'

class CraftCmsSchema {
  private link: HttpLink

  constructor (opts) {
    this.link = new HttpLink(opts)
  }

  public async load () {
    return makeRemoteExecutableSchema({
      link: this.link,
      schema: await introspectSchema(this.link)
    })
  }
}

const CraftSchema = new CraftCmsSchema({
  headers: {
    // this is the API token from CraftQL
    'Authorization': `bearer ${process.env.CRAFT_TOKEN}`
  },
  fetch,
  uri: process.env.CRAFT_URL
}).load()

const fn = async (event, ctx, callback) => {
  const context: any = ctx => ({
    ...ctx,
    version: pkg.version
  })

  const schema = makeExecutableSchema({ resolvers, typeDefs })

  const server = new GraphQLServerLambda({
    context,
    schema: mergeSchemas({
      schemas: [ schema, await CraftSchema ]
    }) as any
  })

  server.graphqlHandler(event, ctx, (error, output) => {
    callback(error, { ...output, statusCode: 200 })
  })
}

// wrap async function behaviour
export const handler = (event, context, callback) => {
  fn(event, context, callback)
}

**Comment by markhuot** [comment]
This is _awesome_ @jgeschwendt! Am I reading the above correctly that `const schema =` is a local schema built in Node and you're stitching CraftQL _in to_ that schema? If so, that's awfully darn neat.

Definitely reach out if you have any trouble with the module approach, I've done something similar a few times and I'm looking for a reason to get it documented in a README or something.

**Comment by jgeschwendt** [comment]
Yup, thats exactly what's happening! The biggest setup that we've built uses a bunch of Services: Auth0, Stripe, Postmark, AWS Step Functions, S3, DynamoDB, etc. with custom-ish resolvers and stitched in CraftQL for all the content management. We love this plugin and all the hard work you've put into it!

**Comment by markhuot** [comment]
Thanks @jgeschwendt! Honestly I've toyed with the idea of adding stitching _in to_ CraftQL itself. I always stop, though, because Node just seems like a much better place to collect those things. It's nice to hear that you've been able to get it working from the other side!

**Comment by narration-sd** [comment]
Have to say this looks  pretty fascinating, @markhuot & @jgeschwendt . 

I'm not  needing stiching at this point, if it's related to other things have built on straight Craft. But the approach for adding functionality tends to open the black box - thanks!

**Comment by markhuot** [comment]
There are more and more ways to do schema stitching lately, but I was using Gatsby for it recently and it was very smooth, https://twitter.com/markhuot/status/1040688333192679424. Node (and JS) provide a really great language for all the async connections to external services.

**Comment by jgeschwendt** [comment]
Okay, so after a little tinkering, here is where I'm at:

CustomModule.php
```php
<?php
namespace modules\custom\google;

use Craft;
use yii\base\Event;

class GoogleModule extends \yii\base\Module
{
    public function init()
    {
        parent::init();

        $guzzle = new \GuzzleHttp\Client(['base_uri' => 'https://maps.googleapis.com']);

        Event::on(\craft\base\Field::class, 'craftQlGetFieldSchema', function (\markhuot\CraftQL\Events\GetFieldSchema $event) use ($guzzle) {
            $googleType = $event->schema->createObjectType('Google');

            $googlePlaceType = $event->schema->createObjectType('GooglePlace');
            $googlePlaceType->addStringField('id');
            $googlePlaceType->addStringField('name');
            $googlePlaceType->addStringField('openingHours'); // FIXME: $googlePlaceType->addJSONField('openingHours');

            $googlePlacesWhereInputType = $event->schema->createInputObjectType('GooglePlacesWhere');
            $googlePlacesWhereInputType->addStringArgument('name');

            $googleField = $event->schema->addField('google')->type($googleType); # this is probably the wrong way to add the google object to the schema
            $googleField->resolve(function ($root, $args) {
                return $root;
            });

            $googlePlaceField = $googleType->addField('place')->type($googlePlaceType);
            $googlePlaceField->addStringArgument('id');
            $googlePlaceField->resolve(function($root, $args) use ($guzzle) {
                $response = $guzzle->request('GET', '/maps/api/place/details/json', [
                    'query' => ['key' => GOOGLE_API_KEY, 'placeid' => $args['id']]
                ]);

                $data = json_decode($response->getBody(), true);
                $result = $data['result'];

                return [
                    'id' => $result['id'],
                    'name' => $result['name'],
                    'openingHours' => json_encode($result['opening_hours']),
                ];
            });

            $googlePlacesField = $googleType->addField('places')->lists()->type($googlePlaceType);
            $googlePlacesField->addArgument('where')->type($googlePlacesWhereInputType);
            $googlePlacesField->resolve(function($root, $args) use ($guzzle) {
                return [];
            });
        });
    }
}
```

Graphiql Editor
<img width="1457" alt="screen shot 2018-10-03 at 4 19 09 pm" src="https://user-images.githubusercontent.com/9220949/46437079-8348b680-c728-11e8-889f-e2618e5d181b.png">

I have a few questions before finishing this up and to make sure I understand what's going on:
1. Is this code getting invoked correctly, or if there is a better way of getting to the schema object or a better event hook to use?
2. Is there a good way to add a JSON scalar? If not using a string will suffice.
3. How can I get the Google object type to be available on the root Query object so it can be called like the query below and make sure it doesn't exist on the Product section (no idea why this is happening).  

```graphql
query {
  google {
    place(id: "ChIJN1t_tDeuEmsRUsoyG83frY4") {
      name
    }
    places(where: { name : "Google" }) {
      id
    }
  }
}
```

**Comment by markhuot** [comment]
> Is this code getting invoked correctly, or if there is a better way of getting to the schema object or a better event hook to use?

This looks nice. I would probably have handled it very similarly.

> Is there a good way to add a JSON scalar? If not using a string will suffice.

Hrm, I like this idea. There's nothing native to GraphQL or even CraftQL but it'd be nice to add. Honestly for 90% of situations using a straight string is probably enough.

> How can I get the Google object type to be available on the root Query object so it can be called like the query below and make sure it doesn't exist on the Product section (no idea why this is happening).

So the event you're currently using is for extending entry types, as you have it inside an `{entries{…}}` field. There's another event that allows you to add on to the top level that is called, `markhuot\CraftQL\Events\AlterQuerySchema::EVENT`. You can use that to add the top level `google` field,

```php
Event::on(\markhuot\CraftQL\Types\Query::class, \markhuot\CraftQL\Events\AlterQuerySchema::EVENT, function (AlterQuerySchema $event) {
  /** @var \markhuot\CraftQL\Types\Query $query */
  $query = $event->query;
  $query->addField('google')->type($googleType);
}
```

**Comment by jgeschwendt** [comment]
Perfect, thanks for all your help. Here is a gist for anyone that wants to see an example
https://gist.github.com/jgeschwendt/6adcdacc920127ee41041aaf01df7387
