### ISSUE TITLE
How to access entry type fields?

### ISSUE THREAD

**Issue by pr1ntr** [markhuot/craftql#175]
Some of my Entries have fields that link to the other Entries. When I use one of these fields, Craftql does not have it in the schema. For instance, I have an entry type named `page` which should link a Page entry, `page` is not present in the schema in graphiQL. There is not even an Id available. This makes it difficult to get relationships.

Using Craft3

**Comment by markhuot** [comment]
Hrm, this should _definitely_ be possible. Here's on example of how I do it,

```graphql
{
  entries(section:blogPost) {
    ...on BlogPost {
      title
      url
      relatedPosts { # this is an Entries field that allows the content author to choose related entries
        url # this is the URL of the related entry
        title # this is the title of the related entry
      }
    }
  }
}
```

If the above doesn't make sense can you attach an example query of what works and what doesn't work and I can help you debug it?

**Comment by pr1ntr** [comment]
I did not set up a fragment for this but here is my query, its dirty but `page` doesn't even register

```query sites {
  sitemap: entries(type: [SitemapNode]) {
    id
  	section {
      name
    }
    type {
      name
    }
    page {
      title
    }
    parent {
      id
      slug
      level
      type {
        name
      }
    }
  }
}
```

**Comment by markhuot** [comment]
Where does the `page` field come from, is that a field in Craft?

Guessing here: tr removing `page` and put `title` on the same level as parent.

**Comment by pr1ntr** [comment]
`pag`e is a field on SitemapNode  that is a type of Structure Section called Sitemap that references another EntryType called `Page` which is a Channel Section

**Comment by markhuot** [comment]
Can you send me a screen shot of this in GraphiQL? Also, can you click Docs in GraphiQL and navigate to entries » page and screen shot what that does in the documentation?

**Comment by markhuot** [comment]
And, if I'm understanding correctly the `...on PagesPage` is not returning what you would expect?

**Comment by pr1ntr** [comment]
That is correct, I think it has to do with this:
![image](https://user-images.githubusercontent.com/1272089/47823248-c99c3000-dd3d-11e8-8bed-dca212ad75e6.png)

page is SitemapNode appears to be an [Int] which makes me think its just an ID. The query above does not work probably because the inline fragment would require me to not filter by SitemapNode. 

What I expected was to have `page` be filled in SitemapNode.

I am actually on vacation atm and one of our devs is also working on this. I'll try to check back soon but I won't be back officially until next wed.

**Comment by pr1ntr** [comment]
I am able to query the correct Data here:
![image](https://user-images.githubusercontent.com/1272089/47823440-b473d100-dd3e-11e8-8303-143886ec26f6.png)


however if i query these things separately the sitemapnodes have not even a queriable ID of their attached pages so I couldn't figure out how to connect the page to the sitemapnode.

**Comment by markhuot** [comment]
Thanks, can you take a screen shot of the `page` field config within the Craft UI so I can see how it's structured?

**Comment by pr1ntr** [comment]
This is what it looks like.

![image](https://user-images.githubusercontent.com/1272089/47935818-156fe600-deb2-11e8-82fa-b7e95b334e2b.png)

**Comment by pr1ntr** [comment]
This is the entry type
![image](https://user-images.githubusercontent.com/1272089/47936033-d3936f80-deb2-11e8-83d4-2787e83a3002.png)

**Comment by pr1ntr** [comment]
bingo, that did it! Thanks so much
