### ISSUE TITLE
Replace GraphiQL with GraphQL Playground

### ISSUE THREAD

**Issue by jgeschwendt** [markhuot/craftql#179]
It would be nice to swap out the GraphQL IDE for something a little more advanced. 

https://github.com/prisma/graphql-playground

**Comment by markhuot** [comment]
Hrm, I've never thought of embedding the entire playground. I've been running the app standalone and it's been fine, though. Is there an advantage to embedding it over just running the app?

**Comment by jgeschwendt** [comment]
I think the biggest advantage is having it available out-of-the-box inside Craft/Browser. For less technical people using the CMS and/or participating in feature planning, they tend to get confused or frustrated when an App needs to be downloaded and understood. 

As a developer, it's nice to have quick access to that interface because it saves the context of that workspace in local storage offering a slightly better DX when working with multiple queries or jumping between projects.

**Comment by markhuot** [comment]
I'm not ready to make this jump _just_ yet. I've been using Playground myself for some time and while I like 90% of it I think it's conceptually more difficult to wrap your head around for beginners. Also, I find the schema browser of Playground more confusing and harder to interact with. E.g., browsing field attributes is much more difficult in Playground.

I'm open to the idea of making this a configuration option at some point. If you're interested in submitting a PR I'm happy to consider it.
