### ISSUE TITLE
Tooltips in GraphiQL?

### ISSUE THREAD

**Issue by StevenLangbroek** [markhuot/craftql#19]
Most GraphiQL instances I've used have tooltips, I don't see them in CraftQL however (also no errors in console etc.), is this a known issue?

**Comment by markhuot** [comment]
Can you grab me a screenshot? I'm not sure I know what you're describing.

**Comment by StevenLangbroek** [comment]
<img width="439" alt="graphiql-tooltip" src="https://user-images.githubusercontent.com/296796/30430458-917e5ca6-995b-11e7-9af9-c60bd6727530.png">

**Comment by markhuot** [comment]
I'm mobile right now so I can't grab you a screenshot, but I _do_ see tooltips in my install of CraftQL.  When you first load the page, there should be an initial request to /api that is the introspection query. Can you see if that query returns the full schema?

**Comment by StevenLangbroek** [comment]
![image](https://user-images.githubusercontent.com/296796/30430946-41edc562-995d-11e7-89fa-100a8664acb7.png)

![image](https://user-images.githubusercontent.com/296796/30430979-6725c046-995d-11e7-9bd5-35c7ca8ffb5a.png)

This looks right to me...

**Comment by markhuot** [comment]
Lol… I'm a dummy. `1.0.0-beta.16` fixes this.

The issue was that I needed to absolutely position GraphiQL and that was causing the `.CodeMirror-hints` to appear _below_ the GraphiQL interface. A `z-index` update to the hints and everything is looking right again.
