### ISSUE TITLE
Specifying a minimum number of entries per entry type in entriesConnection / relatedEntries query

### ISSUE THREAD

**Issue by alexhillel** [markhuot/craftql#190]
I'm new to GraphQL and am enjoying working with your plugin. However, I'm a little unsure if I'm missing something with how I'm approaching related content.

I have an Entry Type which contains relations with a number of different Entry Types. I'd like to be able to use one query to fetch the 5 most recent related entries of Related Entry Type 1, the 6 most recent related entries of Related Entry Type 2, etc.

I'm currently using relatedEntries passing in an array of all the related entry types, with a high limit parameter, then filtering on __typename within my Vue component. However, if the limit parameter is 30, and the 30 most recent entries across the multiple entry types are from the same type, then I wouldn't be getting any values for the other types.

Is it possible to ensure I'm getting a certain number of entries per type with a single entriesConnection query? Or do I need to make multiple requests in this case, which I'd rather avoid if possible to reduce latency?

**Comment by narration-sd** [comment]
@alexhillel  Wonder if you've considered that unlike element-api, a single GraphQL query can contain multiple element results (of any type or kind; don't have to be actually in relation to some 'main' query at all).

Thus you could arrange each of your related types to return on a distinct alias within the main query, each with a limit 5. Your  Vue side could combine those results as you want...

Schematically as I don't recall relation syntax at moment, something like the following perhaps. 

If the fields returned are the same, you could also roll those up into a single fragment, and refer to that for their return on each type...
```
query overAll ($someKey: String) {
    oneType: entries (key: $someKey, relation: rel1) {
        field1
        ....
    }
    anotherType: entries(key: $someKey, relation: rel2) {
        field1
        ...
    }
    ...
}

```

**Comment by alexhillel** [comment]
Perfect. Thank you @narration-sd!
