### ISSUE TITLE
Please release completed features.

### ISSUE THREAD

**Issue by roelvanhintum** [markhuot/craftql#192]
First of all, awesome plugin!!!

Some of the new features, like handling color fields, work fine. Is it possible to release completed features? Right now i'm using dev-master (which scares me).

**Comment by peterhicks** [comment]
I'd like to second this – I'm using https://github.com/markhuot/craftql/issues/119 in my codebase, and I'm also not keen to leave a client pinned on dev-master.

**Comment by markhuot** [comment]
Thanks for he nudge! I have one PR and a small tweak/issue I want to fix and then I’ll cut a release. Should be next week some time.

**Comment by markhuot** [comment]
LOL, marking this as "waiting for release" so I can close the ticket after I cut the release in the next few days.
