### ISSUE TITLE
URL /api not found (Error 404)

### ISSUE THREAD

**Issue by nelhop** [markhuot/craftql#194]
I am running craft 3 in a nanobox docker locally. It is available at `http://mysite.local`.

The `{helloWorld}` query in the CraftQL fails with a HTML 404 error:
![404](https://user-images.githubusercontent.com/1862955/49301240-721bec00-f4c4-11e8-9022-39dcf7a96f90.png)

Same problem with curl: `curl -H "Authorization: bearer xxx" -H "Content-type: application/json" -d '{"query":"{ helloWorld }"}' http://mysite.local/api`

Is there anything I need to configure?

**Comment by markhuot** [comment]
Can you access any of Craft's routes? E.g., is the control panel located at `/admin` or `/index.php/admin`?

You might want to try `/index.php/api` and see if that makes a difference. The most common cause of this issue is the `mod_rewrite` not working under Apache.

**Comment by nelhop** [comment]
Thanks for the hint!

I accessed front- and backend at `http://mysite.local/web/`.
After updating the `document_root` to `backend/web` it works just fine.

**Comment by boxadesign** [comment]
Hi, I am having a similar issue to this.

Within CraftQl I can query data ok and also with curl. However if I go to: mysite.local/api I get a 404.

I'm running apache but am unsure where the issue lies.

Thanks, Matt

**Comment by narration-sd** [comment]
If you're just accessing the api route from a browser, you're going to get refused because you haven't included an authorization token, as you would on curl or other means.

CraftQL ought to return a 401 in this case, rather than a 400, signaling normally what's going on.

This is related to other responses which CraftQL is still a bit loose about  - see #242

**Comment by mdunbavan** [comment]
@narration-sd, @boxadesign, @markhuot 

This issue is still happening for me and I cannot figure out what is going on.

**Comment by Jones-S** [comment]
> Thanks for the hint!
> 
> I accessed front- and backend at `http://mysite.local/web/`.
> After updating the `document_root` to `backend/web` it works just fine.
@nelhop 

I am having the same issue. Redirects seem to work but I also access
frontend and backend the same way:
FE: http://localhost:8888/web/
BE: http://localhost:8888/web/admin/dashboard

So I assume that I have the same problem.
But what do you exactly mean by updating the document_root?
Would that mean I have to change the root folder within MAMP for example?
But where should it point to?
to `/web`?

If I access: 
http://localhost:8888/api
I get:
> The requested URL /api was not found on this server.

And 
http://localhost:8888/web/api
a solid `404`.

Any help is much appreciated.
