### ISSUE TITLE
Could not find an entry with id X

### ISSUE THREAD

**Issue by u12206050** [markhuot/craftql#195]
My upsert Mutation doesn't seem to want to create a new entry only update.

```
mutation createNewProduct($id: Int, $sku: String, $price: Int, $title: String, $in_stock: Int, $description: String) {
  upsertProduct(id: $id, sku: $sku, price: $price, title: $title, in_stock: $in_stock, description: $description) {
    id
  }
}
```

Al I get in return is an error: 
```
{
  "error": "Could not find an entry with id 5"
}
```

When calling it via curl I get:

```
message: Could not find an entry with id 5
category:	 user
```

Any ideas?

**Comment by u12206050** [comment]
So I think I might have "solved" this: upsert can only create a new element if you don't specify an **id**, if you do specify the **id** then it means it is an update.

This means you can not insert a new element with a specific id.

**Comment by markhuot** [comment]
Unfortunately, that is correct. Sorry for any confusion this caused.
