### ISSUE TITLE
There's no license

### ISSUE THREAD

**Issue by terbolous** [markhuot/craftql#2]
Could you add, or specify, what license this is available as?

**Comment by markhuot** [comment]
Yes, thank you, it's been on my list but hasn't made it in yet. I'd like to use the same license as Craft, itself, but need to confirm if that's possible with the Craft folks before I do.

**Comment by markhuot** [comment]
`LICENSE.md` is now in place, https://github.com/markhuot/craftql/blob/master/LICENSE.md
