### ISSUE TITLE
Get related entries

### ISSUE THREAD

**Issue by Wiejeben** [markhuot/craftql#20]
First of all, thanks for writing this amazing plugin!

I was wondering if there is a way to get entries that are related to the current entry. With this I specifically mean for example: news -> comments, where inside comments a relation is defined with news. Now it is very easy to get the news article related to that comment, but how would one go about getting the comments that are related to the news article?

Inside Twig I would usually do something like this: `craft.entries.section('comments').relatedTo(newsArticle)`

**Comment by markhuot** [comment]
Just to confirm, in you example, is `newsArticle` an entry as well, from a separate entries loop.

This isn't currently possible, but I'll look at adding it. More soon.

**Comment by Wiejeben** [comment]
Yes, I guess that would be relevant for most use cases.

**Comment by markhuot** [comment]
This is a fun problem to solve @Wiejeben, thanks for the challenge. One quick note I realized while I was working this through: this is already possible today with a second GraphQL query. The second query would be identical to your `craft.entries` line above. E.g. If your `newsArticle` has an ID of `5` the query would be,

```graphql
{
  entries(relatedTo:5) {
    ...on Comments {
      id
      author {
        name
      }
      commentText
    }
  }
}
```

I _think_ there's a cleaner way to do this, with some sort of `related` field on the `entries` return, but I'm still looking at possibilities there. I'll leave this open until I figure out a nice syntax for that.

**Comment by markhuot** [comment]
This is now implemented on `dev-master`. I added some docs on it to the readme, here: https://github.com/markhuot/craftql#relationships

Note: The syntax from the above comment changed a little: `relatedTo:` now looks for an array. I've updated the above comment.

**Comment by Wiejeben** [comment]
Thanks, that was quick! I think this will do, will give this a try soon!
