### ISSUE TITLE
Error on date field

### ISSUE THREAD

**Issue by StevenLangbroek** [markhuot/craftql#21]
Whenever I add a date field to my query it throws an error. Removing all date fields gets rid of the error... Any idea what's going on?

![image](https://user-images.githubusercontent.com/296796/30512463-b198daca-9af0-11e7-9869-364251b4201b.png)

**Comment by markhuot** [comment]
I'll take a peek. Can you try adding a `@date` afterwards and see if that helps?

```
{
  entries {
    dateCreated @date(as:"r")
  }
}
```

I'm away from the computer for a bit but will look as soon as I have a chance.

**Comment by StevenLangbroek** [comment]
Hm yeah that fixed it...

**Comment by markhuot** [comment]
`1.0.0-beta.17` should fix this. The issue was I had a bad check for date fields that _didn't_ include a directive.
