### ISSUE TITLE
CraftQL 1.3.0 causing errors on Craft 3.0.x

### ISSUE THREAD

**Issue by brandonkelly** [markhuot/craftql#217]
v1.3.0 is referencing Local volumes’ `uid` property, which wasn’t available until Craft 3.1.0.

You may want to re-tag `1.3.0` with the `craftcms/cms` requirement in composer.json changed to `^3.1.0`, so people still running Craft 3.0.x aren’t able to update to it.

**Comment by markhuot** [comment]
Ah, yup, thanks for that. I'll make this change.

**Comment by markhuot** [comment]
Release 1.3.1 should fix this issue. Instead of bumping the version I just added checks around my usage of `->uid`.

Separately I'm working on 1.4.x which will be Craft 3.1.x dependent. But this was an easy workaround to keep 3.0.x working for the time being.
