### ISSUE TITLE
"error": "SystemTypeEnum has value with invalid name: \"32bit\"...

### ISSUE THREAD

**Issue by swthate** [markhuot/craftql#219]
**Running any query, including the simple `{ helloWorld }`, returns the following error:**

```
{
  "error": "SystemTypeEnum has value with invalid name: \"32bit\" (Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"32bit\" does not.)"
}
```

**devMode** true
**Craft** 3.1.7 (pro trial)
**CraftQL** 1.3.1 (trial)
**PHP** 7.2.14 (I'm using Homestead which defaults to 7.3.x. I changed the current dev site to use 7.2 because I have seen others have unrelated issues with 7.3 and was hoping that'd be a simple fix, but the error persists across both versions)

When I run the sample `curl` command my terminal is flooded with what looks like the markup of an html page. I do have a token created with the name `dev` and it has full access.

**Comment by markhuot** [comment]
You probably have a drop-down field that has `32bit` as the value of one of the options. This is invalid in GraphQL so that's why you're getting the error. Is it possible to update `32bit` to be something else?

**Comment by swthate** [comment]
Oh my gosh. Yes I do have a drop-down field with a 32bit value. It's for selecting 32 vs 64 bit OS values. Changing the value to `bit32` fixed it.

Thanks!
