### ISSUE TITLE
Support for OPTIONS method

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#22]
Right now, I can seemingly only hit the `/api` endpoint locally, since the OPTIONS method doesnt actually hit craftql. Could the OPTIONS method be added to allow remote apps to also query craftql?

**Comment by markhuot** [comment]
I just added support for `OPTIONS`. You can define the `allowedOrigins` config in `config/craftql.php`, if you need it.

<img width="379" alt="screen shot 2017-09-28 at 12 18 51 pm" src="https://user-images.githubusercontent.com/48975/30978021-4f2ec77c-a447-11e7-8dcf-ac025b19d9f0.png">

You'll need to update composer with `markhuot/craftql:dev-master` to get this all working. I'll get it tested and tagged to a stable release later today.

**Comment by markhuot** [comment]
`1.0.0-beta.19` has full support for OPTIONS requests.
