### ISSUE TITLE
Add a public GraphiQL route

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#226]
It would be great if there were a public controller/route that rendered GraphiQL, outside of the CP.

We've often granted access to CraftQL to other devs via tokens, without a Craft account/login.

If we could point them to an endpoint where they could put in their token and use GraphiQL outside of the CP, that would be ideal.

**Comment by markhuot** [comment]
Interesting, how would this differ from them using something like https://github.com/prisma/graphql-playground with their same token?

I'm not discounting the idea, I like it, just curious if there aren't better ways?

**Comment by timkelty** [comment]
@markhuot ah, I knew about desktop versions (e.g. https://insomnia.rest/graphql/), but didn't know about graphqlbin.com!

For some reason my queries work (once I put the `Authorization` stuff in the HTTP headers, but the schema/docs never load.

Might be CORS issues, seeing `x-apollo-tracing` CORS errors in the console…

**Comment by timkelty** [comment]
Hmmm yeah it works fine with the local/desktop version

**Comment by markhuot** [comment]
Yup, it must be a CORS issue if it works locally.

You could try setting `'allowedOrigins' => '*'` in your `config/craftql.php` to work around that. Or, more securely, set it to `www.graphqlbin.com`, probably.

**Comment by timkelty** [comment]
👍 well this is good enough for me to pass on to api consumers, thanks!
