### ISSUE TITLE
Registering schema with Apollo Engine

### ISSUE THREAD

**Issue by tinchalamo** [markhuot/craftql#229]
Has anyone been able to [add their schema to the Apollo registry](https://www.apollographql.com/docs/platform/schema-registry.html)? I'm stuck on the **[Pushing a service](https://www.apollographql.com/docs/platform/schema-registry.html#publish)** step since I'm unsure on how to pass the CraftQL token to this command:

```
apollo service:push --key="<API_KEY>" --endpoint="https://example.com/graphql"
```

The `<API_KEY>` part of the command is for Apollo Engine so it knows which service to connect it to.

**Comment by markhuot** [comment]
You can pass `--header` to the `apollo service:push` command to specify additional heads for the introspection query. https://github.com/apollographql/apollo-tooling#apollo-servicepush

E.g.,

```bash
$ apollo service:push --key="<API_KEY>" --endpoint="https://craftql.com/api" --header="Authorization: bearer <CRAFTQL_TOKEN>"
```

**Comment by tinchalamo** [comment]
That did the trick, thanks Mark!
