### ISSUE TITLE
Query entries with a structure from categories

### ISSUE THREAD

**Issue by nelhop** [markhuot/craftql#233]
I have tree structured categories which represent a hierarchy.

__Query:__
```
query ContactStructure {
  ContactStructure: categories(group: contact, level: 1)  {
    level
    title
      children {
        level
        title
      }
  }
}
```

__Result:__
```
{
  "data": {
    "ContactStructure": [
      {
        "level": 1,
        "title": "Executive Board",
        "children": [
          {
            "level": 2,
            "title": "First Chairmanr"
          },
          {
            "level": 2,
            "title": "Secont Chairman"
          },
          {
            "level": 2,
            "title": "Secretary"
          },
        ]
      },
  }
}
```

In a structure (may also be a channel) I have multiple entries (persons) who belong to one or more categories.
How can I query the persons in their tree structure (see result above)?

**Comment by markhuot** [comment]
Using `categoriesConnection` should get you want you want. The `*Connection` fields add a layer of indirection to the result so you can pull related elements out like so,

```graphql
{
  categoriesConnection(group:testNestedCategoryGroup, level:1){
    edges{
      node{
        id
        title
      }
      relatedEntries{
        edges{
          node{
            title
          }
        }
      }
    }
  }
}
```

In the above the `node` on line 4 is the category. That'll pull back any info like the level and title of the category. Then the `relatedEntries` field will pull any entries _related_ to that category. That should get you the people related to the First Chairman, for example.

You can also insert a `children` field in there to mirror your current query,

```graphql
{
  categoriesConnection(group:testNestedCategoryGroup, level:1){
    edges{
      node{
        id
        title
      }
      children{
        edges{
          node{
            title
          }
          relatedEntries{
            edges{
              node{
                title
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by nelhop** [comment]
Works like a charm. Thank you very much @markhuot !
