### ISSUE TITLE
`internal server error` after deleting a category-group in craft

### ISSUE THREAD

**Issue by nelhop** [markhuot/craftql#234]
I have deleted an unused category-group in craft. Since then the CraftQL api responds with a `internal server error`.
Deactivating categories in the token scopes let run the api correct again. But since I need categories for other queries this is no option.

The GraftQL Plugin prompts: 
```
{
  "error": "Trying to get property 'handle' of non-object"
}
```

How can I get CraftQL get up running again?

**Comment by nelhop** [comment]
Apparently the category-group was not as unused as I thought. It was still referenced in a section entry. After removing it (really everywhere) the error is gone.
Sorry for the unnecessary Issue! :disappointed:

**Comment by intensr** [comment]
how did you detect it since the error itself gives no clue whatsoever, were using a lot entries and fields and its hard for me to detect what causes the error

**Comment by simeon-smith** [comment]
Running ./craft gc/run is a workaround that seems to fix this issue.
