### ISSUE TITLE
Querying for all categories, tags

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#25]
Cannot see to find a way to fetch categories or tags without going through an entry first. Is there a simple method to get categories, either all of them, or by group?

**Comment by markhuot** [comment]
I’m working to add this in. Both tags and categories will have a top level query field, like entries do.

**Comment by markhuot** [comment]
This is now possible in `1.0.0-beta.23`. There are two ways to get categories and tags. The easy way,

```graphql
{
  categories { # this takes any arguments that `craft.entries` takes
    id
    title
  }
}
```

Or the more complex (but more feature complete) method,

```graphql
{
  categoriesConnection {
    edges {
      node { #this is the category
        id
        title
      }
      relatedTo(limit:5) { # you can limit these, as necessary
        entries { #this is an array of entries related to the category
          id
          title
        }
      }
    }
  }
}
```

This method allows you to grab a category, as well as any entries related to the category.
