### ISSUE TITLE
access custom fields of assets

### ISSUE THREAD

**Issue by nelhop** [markhuot/craftql#252]
I added a custom field `copyright` to my assets field layout. How can this be accessed in the query?

I expected this query to work:
```graphql
query startsliders{
  startsliders: entries (
    section:[start_slider],
    ) {
    id
    title
    copyright
  }
}
```
But it prompts: `Cannot query field \"copyright\" on type \"EntryInterface\".`

**Comment by markhuot** [comment]
What's the name of your assets field? Also what is the name of your assets volume? You'll probably need something along these lines,

```graphql
{
  entries {
    ...on EntryType {
      title
      assetFieldHandle {
        ...on VolumeHandle {
          copyright
        }
      }
    }
  }
}
```

**Comment by nelhop** [comment]
Thanks for the hint! I missed out the `VolumeHandle`.
