### ISSUE TITLE
Support For Image Transforms

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#26]
Taking a look through the current schema it doesn't appear like there is support for image transforms.  Is currently support or planned support for image transforms?

**Comment by markhuot** [comment]
Yes, it’s definitely planned. How would you envision it working? Maybe,

```graphql
{
  entries {
    ...on Post {
      imageFieldHandle {
        thumbnail: url(transform: “thumb”)
        poster: url(crop: {width: 1280, height: 720})
      }
    }
  }
}
```

**Comment by markhuot** [comment]
1.0.0-beta.21 adds support for image transforms, largely following the above spec. The only tweak is that named transforms are referenced by enum, not a string. For dynamic crops, use the second format specifying the exact dimensions.

```graphql
{
  entries {
    ...on Post {
      imageFieldHandle {
        thumbnail: url(transform: thumb)              # reference the handle of a named transform
        poster: url(crop: {width: 1280, height: 720}) # dynamic `crop`, `fit`, or `stretch`
      }
    }
  }
}
```

**Comment by bzin** [comment]
Is this already available @markhuot? The version of the plugin in the store is 1.0.0, but the transform is not working for me. It's returning me a `null` value.
