### ISSUE TITLE
RC1 - Uncaught TypeError: Cannot read property 'parentNode'

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#27]
I updated to the RC1 branch and found an error when attempting to use graphiql from the control panel:

`Uncaught TypeError: Cannot read property 'parentNode' of null
    at browse:422`

**Comment by markhuot** [comment]
I haven’t cut a stable release yet, but `dev-master` should fix that.

**Comment by edolyne** [comment]
@markhuot 👍 switching to dev-master solved the issue.
