### ISSUE TITLE
TypeScript: Failed to Connect

### ISSUE THREAD

**Issue by jacksoncool** [markhuot/craftql#288]
After I install Craftql, i get the following error in the Graphiql: Typescript: failed to connect in the Graphiql. 

This error still occurs even after I set up my token, and set permissions to different sections.

**Comment by narration-sd** [comment]
@jacksoncool  You should probably include your details of what CraftQL version, what Craft version, what other plugins you may be running, etc..

CraftQL has been working for many months, and your connect issue seems unusual. You can run iql without a specified token from the icon on the left vertical menubar the Craft CP -- see if it shows without the error from there. 

If so, run a query as below, to assure general health:
```
query {
  helloWorld
}
```

If you continue problems, I'd disable other plugins, as a start to finding issues. Obviously JavaScript has to work in your browser, in case you're running  NoScript, etc.. I'm in fact using CraftQL on several sites just at the moment, works normally...

**Comment by jacksoncool** [comment]
I have the latest version of CraftQL 1.3.2 ( a fresh install) and the latest version of Craft CMS (Craft Solo 3.1.32.1.) Additionally, I did previously try to query helloWorld (the first thing i tried) and got the same error.

**Comment by jacksoncool** [comment]
figured out the url i was accessing the admin with was different than the base url inside the admin. So that's why i wasn't getting anything.
