### ISSUE TITLE
Add Support For Simple Maps

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#30]
I've been taking a look at [Simple Maps](https://github.com/ethercreative/simplemap), thoughts about adding this in?

possible schema:

```graphql
fragment mapContent on MyPageType {
  mapField {
    lag
    lng
    zoom
    address
    parts {
        streetNumber
        route
        neighborhood
        political
        locality
        administrativeAreaLevel1
        administrativeAreaLevel2
        country
        postalCode
    }
  }
}
```

**Comment by markhuot** [comment]
Yup, love it. Should just take a new Behavior in the `fields` folder. I’ll look at adding it in.

**Comment by markhuot** [comment]
:point_up: made a request to have this added to the Simple Maps repo. If it’s denied I can add it here, instead.

**Comment by Tam** [comment]
[Added in SimpleMap v3.1.0](https://github.com/ethercreative/simplemap/releases/tag/v3.1.0)!

**Comment by markhuot** [comment]
Thanks @Tam!

![so excited](https://media.giphy.com/media/61KXXDgl7rZPW/giphy.gif)
