### ISSUE TITLE
Error after purchasing license > "Craft Pro is required for this"

### ISSUE THREAD

**Issue by ca-miked** [markhuot/craftql#319]
Unable to run any queries at all in craft without getting "Craft Pro is required for this". Is this plugin not compatible with the core GraphQL api as of this version?

- Craft CMS 3.3.2
- CraftQL Plugin version 1.3.4

Help?

**Comment by narration-sd** [comment]
You're talking to the built-in GraphQL API. 

You want to connect instead the CraftQL API, so you'll need to set it or the internal one to a recognizably different url path. 

Doc on either; CraftQL's is on its github readme, config file is easy. 

Can't help more as on phone; Dev machine is having its Windows reloaded - don't ask 🙃

**Comment by ca-miked** [comment]
Got it. thanks!
