### ISSUE TITLE
GraphQL\Error\InvariantViolation error when devmode is enabled

### ISSUE THREAD

**Issue by daltonrooney** [markhuot/craftql#324]
I am trying to debug a problem that prevents CraftQL from working when devmode is enabled.  Any query in the graphiql returns:

```
{
  "error": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"\" does not.\n\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"\" does not."
}
```
Running ./craft craftql/tools/print-schema > ./file.graphql from the CLI returns the following exception:

```
Exception 'GraphQL\Error\InvariantViolation' with message 'Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.'

in /app/craft/vendor/webonyx/graphql-php/src/Type/Schema.php:440

Stack trace:
#0 /app/craft/vendor/markhuot/craftql/src/Services/GraphQLService.php(124): GraphQL\Type\Schema->assertValid()
#1 /app/craft/vendor/markhuot/craftql/src/Console/ToolsController.php(570): markhuot\CraftQL\Services\GraphQLService->getSchema(Object(markhuot\CraftQL\Models\Token))
#2 [internal function]: markhuot\CraftQL\Console\ToolsController->actionPrintSchema()
#3 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /app/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /app/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('print-schema', Array)
#6 /app/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('print-schema', Array)
#7 /app/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('craftql/tools/p...', Array)
#8 /app/craft/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('craftql/tools/p...', Array)
#9 /app/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('craftql/tools/p...', Array)
#10 /app/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /app/craft/craft(22): yii\base\Application->run()
#12 {main}
```

And obviously the schema is never generated. Can anyone give me a hint as to where the problem might be and how to troubleshoot?

**Comment by daltonrooney** [comment]
Incredibly, just seconds after I posted this, I discovered an undocumented setting:

`"throwSchemaBuildErrors" => true`

Which gave me more information:

```
{
  "error": "The field \"Columns\" (columns) contains an invalid value, `1`. Field values must start with a letter or underscore followed by any number of letters, numbers, and underscores. For the nerds, that's /~^[_a-zA-Z][_a-zA-Z0-9]*$~/"
}
```

Easy enough, I changed the field values, but apparently that didn't fix the problem. Now I'm back to 

```
{
  "error": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"\" does not.\n\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"\" does not."
}
```

**Comment by narration-sd** [comment]
That's a great find - how about considering what plugins you may be using?

Not all work with CraftQL, and maybe one of them is what isn't generating/interrupting Schema generation??

**Comment by narration-sd** [comment]
The more I look, the more I think I shouldn't have commented here, but maybe this...

What CraftQL does with Craft devMode true, is check-generate the Schema on each request. So if you're changing a field _value_, this may not be the thing -- it would have to be the Schema definition for that field.

But that's enough wild guessing :) . I guess...

**Comment by daltonrooney** [comment]
Found it! The culprit was a table field within a matrix field. The table field had blank column handles, and once we fixed that, the schema would generate again. 

It would be great if this debug setting were documented somewhere! I’ll see if I can put together a PR.

**Comment by daltonrooney** [comment]
The other weird thing is that this was all working fine up until last week. Must have something to do with Craft 3.3 and the upgrade of the underlying GraphQL library.

**Comment by narration-sd** [comment]
Great catch -- and there's been a lot of monkeying with Matrix recently, to fix issues raised, thus might be a good thought.

I don't think it then has to do with the embedded Craft GraphQL. Though possibly with the webonyx/graphql-php basis for CraftQL which was upgraded for compatibility, and may have better checks, and maybe that's what you meant.

Nice idea about the doc PR, too -- Cheers
