### ISSUE TITLE
Are tokens not stored in project.yaml?

### ISSUE THREAD

**Issue by sunscreem** [markhuot/craftql#330]
Everything is working nicely locally.

I've deployed to production and I'm getting a `not-authorised`.

If I go and put the site into dev mode I can see that the token I created has been removed because it wasn't captured in the project.yaml.

Is this correct? It's a serious pain as I have to turn on dev mode just to get into settings to duplicate the key?

**Comment by sunscreem** [comment]
Update - just found this:

https://github.com/markhuot/craftql/issues/250

Anyone know if this is being worked on?

**Comment by brandonkelly** [comment]
@sunscreem If you are able to use Craft’s built-in GrahpQL API, we have started storing schemas in the Project Config in 3.4 (currently in Beta). See craftcms/cms#4829

**Comment by sunscreem** [comment]
Thanks @brandonkelly  - I had to switch to using this as built-in one doesn't support a specific type query I need just now.
