### ISSUE TITLE
Curl request format

### ISSUE THREAD

**Issue by davorpeic** [markhuot/craftql#34]
Hi Mark,

awesome plugin, played a little bit and I love it. I'm having issue on how to format curl request for more "advanced" query, example query for helloWord works, but I'm trying to pull simple news entries for example and can't get to find the correct format to post to curl. Any ideas how to format something like this?

```
{
  entries(limit:5) {
    ...on News {
      uri
      title
      body
    }
  }
}
```

thanks

**Comment by davorpeic** [comment]
I tried something like this
```
curl -H "Authorization: bearer mJvfCk7XyF9g5LqxCliSyqW_ylL5VOmR0D4_Q9d1Occ1tsnWkk_shycJFAlnYrq6" -H "Content-type: application/json" -d '{"query":"{ entries(limit:5){...on News {title}} }"}' http://craft3-playground.dev/api
```

But I get 
```
{"errors":[{"message":"Cannot query field \"entries\" on type \"Query\".","category":"graphql","locations":[{"line":1,"column":3}]},{"message":"Unknown type \"News\".","category":"graphql","locations":[{"line":1,"column":26}]}]}
```

I'm guessing I need to escape maybe some parts of the query?

**Comment by markhuot** [comment]
When you generate the token you need to click `Scopes` to enable the fields you'd like to search. It defaults to "very secure" and by not enabling any fields.

![screen shot 2017-12-05 at 11 08 02 am](https://user-images.githubusercontent.com/48975/33616988-94b52008-d9ac-11e7-9665-601eea18aade.png)

**Comment by davorpeic** [comment]
Makes totally sense, and it works... Didn't planned this, but I already see how my day will go 😄 

![postman](https://user-images.githubusercontent.com/694091/33617139-8bb00552-d9a4-11e7-96df-cc62db578cec.png)

Once again, very useful and so much desired plugin!!

**Comment by davorpeic** [comment]
Maybe would be useful to return different statuses (401 for example) when you don't access to some section, so we can take advantage of automatic error/catch handling in remote app for example. But if you return several errors/types maybe it would be hard to determine which one, hmm.

ps. I'm testing this in multilanguage enviorment and see some deprecation errors `The “locale” element query param has been deprecated. Use “site” or “siteId” instead.`

**Comment by markhuot** [comment]
> Maybe would be useful to return different statuses (401 for example) when you don't have access to some section, so we can take advantage of automatic error/catch handling in remote app for example. 

Unfortunately, the error response here is driven by the upstream `webonyx/graphql-php` library. I usually see GraphQL shove errors in to JSON instead of using actual HTTP status codes. If you have an example where you're seeing something different, I'd love to inspect it and see if there's a paradigm to follow.

> I'm testing this in multilanguage enviorment and see some deprecation errors The “locale” element query param has been deprecated. Use “site” or “siteId” instead.

Thanks for the note. If you have a moment, it'd be great to open this as a new issue so I can get it squared away. Locale support is definitely one of the unfinished pieces of this thing, still.

**Comment by davorpeic** [comment]
Oh ok, didn't know that, I have very limited practical experience with graphql, but if I see something will post it. Sure, will open new issue :)
