### ISSUE TITLE
Access to Globals & Site Info

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#39]
Is it possible to query Globals and Site specific info via the schema at this point?

**Comment by markhuot** [comment]
Sure is! I'll work on adding it in.

**Comment by markhuot** [comment]
This is part of a major refactoring over on the `event-registration` branch, which is why it's taking so long. I'll update you as soon as it's ready.

**Comment by markhuot** [comment]
Speaking of which, you can switch to `dev-event-registration` to try this out. It's working for querying now. I haven't implemented mutations yet. It includes all of the fixes we're working on in other tickets for enum/dropdown fields as well as a top level,

```graphql
{
  globals {
    nameOfGlobalSet {
      fieldOnGlobal
    }
  }
}
```

**Comment by edolyne** [comment]
@markhuot I'll give this a try this evening, thanks for the update

**Comment by edolyne** [comment]
@markhuot It looks like with this refactor that plugins may need to update their integration? I'm noticing that [Simple Map](https://github.com/ethercreative/simplemap) integration now thinks it's a string.

**Comment by markhuot** [comment]
You’re correct. This refactor should make it easier for plugins, like SimpleMap to integrate with CraftQL. As soon as this refactor stabilizes I’ll make a PR on the SimpleMap repo with some suggested updates.

**Comment by edolyne** [comment]
@markhuot wanted to check in and see if you have a potential timeline on when the refactor is going to be merged in.

**Comment by markhuot** [comment]
I think it’s ready to go. Needs some more testing, but not too much longer.

**Comment by markhuot** [comment]
`dev-event-registration` is now feature complete. I'm working on beefing up the test class before merging.

**Comment by edolyne** [comment]
Sounds great, I'll had taken a look at it last night and everything looks good. I think the only holdout that I have from running this branch is the SimpleMap field.

**Comment by markhuot** [comment]
I'm planning on submitting a PR to SimpleMap as soon as I merge `event-registration` in to `master`. That PR is ready to go: https://github.com/ethercreative/simplemap/compare/v3...markhuot:v3. I'll merge it as soon as I'm able.

**Comment by edolyne** [comment]
No rush, also that PR looks like it should be pretty easy for developers to add CraftQL support in their plugins.

**Comment by markhuot** [comment]
`1.0.0-beta.27` is tagged with full support for querying and mutating globals.
