### ISSUE TITLE
Dropdown Fields Returning Error

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#40]
When querying a dropdown field, the following error is returned:

`"message": "Expected a value of type \"BackgroundColorEnum\" but received: \"background--primary\"",`

`"message": "Expected a value of type \"ReduceRemoveSpacingEnum\" but received: \"reduceSpacingTopBottom\"",`

---
### Craft & CraftQL versions:

Craft - `RC3`
CraftQL - `dev-master`

**Comment by markhuot** [comment]
Hrm, looks like I need to do some protection on the dropdown values. GraphQL has much more strict rules than Craft does, which is causing this.

**Comment by markhuot** [comment]
Okay, `1.0.0-beta.24` should fix this issue.

**Comment by edolyne** [comment]
@markhuot Looks like it's returning values now, but the values returned don't match the value from the field.

example:

`reduceSpacingTopBottom` returns as `reducespacingtopbottom`
`background--primary` returns as `backgroundPrimary`

**Comment by markhuot** [comment]
`background--primary` isn't a valid ENUM value so I can't return that, as is… hrm. Maybe an Enum isn't the way to go for drop-downs…?

Not sure why `reduceSpacingTopBottom` is losing the casing, though, I'll look in to that.

**Comment by markhuot** [comment]
`1.0.0-beta.25` fixes the casing issue you highlighted.

I'm not sure what to do about the hyphen issue, though. GraphQL won't allow hyphens in enum values. I could just have it return a string, but then I wouldn't be able to validate it on mutation/input. E.g.,

```graphql
{
  upsertPost(
    title: "foo"
    dropdownField: "literally, anything, could be here"
  ) {
    id
  }
}
```

_With_ enums we have some protection,

```graphql
{
  upsertPost(
    title: "foo"
    dropdownField: someValidGraphQLEnum #anything else would fail before data even gets to Craft
  ) {
    id
  }
}
```

I'll need to think on this a bit… I'm open to any ideas you may have.

**Comment by edolyne** [comment]
@markhuot Thanks for the quick fix. I appreciate the ability to validate the return type and then handle the variable in code appropriately. This might be an edge case that I was using the dropdown field to insert the value into the `className`.

**Comment by markhuot** [comment]
Thanks @edolyne. I'm going to close this ticket because we've fixed the incorrect casing on valid values.

One note on the invalid values: you can get the label of the input, if that helps like this,

```graphql
{
  entries(id:2){
    ...on Stories{
      id
      title
      socialLinks #enum field, returns listOf enum values
    }
  }
  __type(name:"SocialLinksEnum"){ #the enum field I'm curious about
    enumValues{
      name # the value of the enum, maybe `myFieldValue`
      description # the label of the enum, maybe `My Field Value`
    }
  }
}
```

I _wish_ there was some way that I could return the raw value inside `enumValues` but GraphQL doesn't provide any way to extend that with native enum's.

**Comment by markhuot** [comment]
At some point in the future I may consider subclassing the Enum type, allowing us to return the raw value. I've noted this in [the roadmap](https://github.com/markhuot/craftql/blob/master/README.md#roadmap).
