### ISSUE TITLE
wont install

### ISSUE THREAD

**Issue by keithmancuso** [markhuot/craftql#5]
trying to install but getting an issue with minimum-stability

`composer require markhuot/craftql`

```
[InvalidArgumentException]
  Could not find package markhuot/craftql at any version for your minimum-stabil
  ity (beta). Check the package spelling or your minimum-stability

```

Checked the projects minimum-stability and its set to `beta` and i get the same error when i change it to `dev`

seems like you might need to release a version on composer?

**Comment by markhuot** [comment]
I just tagged `1.0.0-beta.2` which _should_ fix this. It's on Packagist now too. I verified it with,

```bash
$ composer create-project craftcms/craft test && cd test
$ composer require markhuot/craftql
```

☝️ that installed as I would have expected with `-beta.2`.

**Comment by keithmancuso** [comment]
Perfect!  Thanks Mark, excited to play around with it.

**Comment by devanflaherty** [comment]
Hey there, I'm receiving the same error as above on the RC build of Craft 3.

**Comment by gerardoboss** [comment]
> I just tagged `1.0.0-beta.2` which _should_ fix this. It's on Packagist now too. I verified it with,
> 
> ```shell
> $ composer create-project craftcms/craft test && cd test
> $ composer require markhuot/craftql
> ```
> 
> ☝️ that installed as I would have expected with `-beta.2`.

Hi thank you for your support, I have the same problem as well. :-)
