### ISSUE TITLE
Checkbox field appears as enum, not an array of enums

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#50]
A new checkbox field is appearing as a straight enum and not an array of enums:
https://www.dropbox.com/s/198nqr89mmoc3z4/7r51ptbm.png?raw=1

```
"message": "Argument \"productFeed\" has invalid value [microsite].\nExpected type \"ProductFeedEnum\", found [microsite].",
```

My guess is checkbox should support an array of values, not a single value.

**Comment by markhuot** [comment]
Is this when an issue when using the checkboxes field as an argument to an `{entries(checkbox:[]){...}}`?

**Comment by markhuot** [comment]
Can you confirm for me if this even works in a regular `.twig` template? If I try to do `craft.entries.checkboxesField('possibleValue').count` I always get `0`.

**Comment by askogrand** [comment]
Let me check on both of those and get back to you. Could very well be a limitation of craft

**Comment by askogrand** [comment]
It seems as if you need to either do search on entries, or use `contains` on a specific entry, but `contains` wont work on an entire entries look up.

**Comment by markhuot** [comment]
Well foo. Sounds like it'd be a good FR for the https://github.com/craftcms/cms repo, though!
