### ISSUE TITLE
Batch upserts

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#52]
Not sure if I just don't know how to do this, or if this is a FR :)
Ultimately I'm looking perform an upsert with a condition (emulating `UPDATE x SET fieldA fieldB where y in sql`)

Not exactly sure how this is approached via GraphQL in general.
Does the upsert need to be nested within a query?

**Comment by markhuot** [comment]
Hrm, interesting… right now the only `where` that CraftQL supports is `where id=123`. However, we've got some fields exposing themselves on the `{entries…` query I could look at adding them to mutations as well. Before I go down that path, though, what sort of `where y in sql` are you trying to support?

**Comment by timkelty** [comment]
My immediate need was testing against some element's attributes (section) and updating the an element field of the resulting set.

I'm admitted very green to mutations in graphql in general, so I'm not sure the convention, or how this might even be done ¯\_(ツ)_/¯

**Comment by markhuot** [comment]
I don't know that GraphQL has a "best practice" for updating multiple entries at once. However, it'd fit in to the schema quite nicely. For example, right now we have, `upsert{EntryType}(…)` which looks for a single entry to upsert and either updates it or inserts it. We could add,

```graphql
mutation {
  upsertMultiple{EntryType}(id:[1,2,3], customField:"value") {
    id
    title
  }
}
```

That would return an array of the updated entries… I like this approach, but it'll take a little bit to get implemented.

----

In the meantime, your approach of getting multiple IDs and running them should work. I _think_ you'll have to run them separately though. GraphQL doesn't like running multiple `mutation {…` blocks in one query.

**Comment by markhuot** [comment]
An example for you, graph.cool only supports updating a single node at a time,

https://www.graph.cool/docs/reference/graphql-api/mutation-api-ol0yuoz6go/#updating-a-node

**Comment by timkelty** [comment]
Thanks mark! I'll stay tuned.

**Comment by timkelty** [comment]
I wonder if something like this could work for even more flexibility?

```
mutation {
  upsertMany{EntryType}(query:{EntryInterface}, customField:"value") {
    id
    title
  }
}
```

**Comment by markhuot** [comment]
I like that quite a bit… I'm wondering if `upsert{EntryType}` should just be updated to use `query`, instead… 🤔

**Comment by timkelty** [comment]
Oh that might make sense!

**Comment by markhuot** [comment]
`dev-master` now includes a `query:` argument that allows to you set the search criteria. So, you could do the following,

```graphql
mutation {
  upsertEntryType(query:{customField:123} title:"New Title In Here") {
    # ...
  }
}
```

Note, this still calls `->one()` before setting any data. It won't allow batch updates yet, but it's something I'm looking at.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes the new `query:` argument on upserts. It does not include the ability to update multiple entries at once, mainly because Yii does not allow us to update multiple entries at once. If this is still a need please open a new ticket and we can tackle it there.
