### ISSUE TITLE
matrix fields with the same name have conflicting types

### ISSUE THREAD

**Issue by laian** [markhuot/craftql#54]
If you have two matrix block types with fields with the same name, but different types, graphql gives an error about conflicting types:

```
{
  entries(section:[section-with-matrix]) {
    ...on SectionWithMatrix {
      title
      url
      matrixField {
        ...on SectionWithMatrixType1 {
          # is a string
          blurb
        }
        ...on SectionWithMatrixType2 {
          # is a redactor rich text
          blurb {
            content
          }
        }
      }
    }
  }
}
```

Is this a real issue, or am I using it wrong?

**Comment by markhuot** [comment]
This is a real issue. I didn’t even think Craft allowed this. I’ll get a fix in place shortly.

**Comment by markhuot** [comment]
Ah, digging deeper I think this is a GraphQL "issue" not a CraftQL issue. GraphQL doesn't like to return multiple fields of the same name with different types. The error you're seeing is actually on the return, not in the CraftQL schema. That means it's also easy to fix. To return two `blurb` fields of different types you'll need to alias them. When looping over a Matrix field I like to include the `__typename` too,

```graphql
{
  entries(section:[section-with-matrix]) {
    ...on SectionWithMatrix {
      title
      url
      matrixField {
        ...on SectionWithMatrixType1 {
          type: __typename # is a string
          type1Blurb: blurb
        }
        ...on SectionWithMatrixType2 {
          type: __typename # is a redactor rich text
          type2Blurb: blurb {
            content
          }
        }
      }
    }
  }
}
```

**Comment by laian** [comment]
Thanks @markhuot !
