### ISSUE TITLE
authorization error with the default hello world request + default token

### ISSUE THREAD

**Issue by laian** [markhuot/craftql#56]
Using the default demo curl command under the plugin settings:

```
curl -H "Authorization: bearer <my_token>" -H "Content-type: application/json" -d '{"query":"{ helloWorld }"}' my-craft-domain.com/api
```

I'm getting:
```
{"errors":[{"message":"Not authorized"}]}
```

Did I do something wrong with setup?

**Comment by markhuot** [comment]
Make sure that the URL you have in CURL and the URL you have in Craft’s site settings are the same.

Also, can you try a lowercase `authorization` header?

**Comment by markhuot** [comment]
Hrm, yea, I tried this with all the upper/lowercase combos I could think of and it always worked for me. I copied the `curl` command directly out of the CraftQL plugin settings too. If you're in the #craftcms Slack room grab me whenever you're available and maybe we can do a quick chat/screen share.

**Comment by markhuot** [comment]
Check #58, which has a tip in case you’re running PHP in FastCGI mode.
