### ISSUE TITLE
Querying Redactor Field Type throws error

### ISSUE THREAD

**Issue by menberg** [markhuot/craftql#57]
Hi Mark!

I'm having troubles querying a Redactor Field Type.

In the following example, **postMessage** is a Redactor text field. Querying only the id of post entries works, but querying the postMessage field throws an error.

```
{
  entries(section: [posts], limit: 5) {
    ... on PostsPost {
      id
      postMessage
    }
  }
}
```

```
{
  "error": "String cannot represent non scalar value: instance of craft\\redactor\\FieldData"
}
```

Is this a known issue? Are Redactor fields maybe not yet supported?

Greetings and thanks for your great work so far!

**Comment by menberg** [comment]
I just found commit https://github.com/markhuot/craftql/commit/fd19c3a0f7353464ecab32112f0e6c7da46f84db which adds Redactor support. I'm on version 1.0.0-beta.27. Is this commit already included or should I wait for a new release?

**Comment by markhuot** [comment]
Redactor support has not made it's way to a stable release, yet. You can update the version in your `composer.json` to `dev-master` or wait for the next stable release (should be this week).

**Comment by markhuot** [comment]
`1.0.0-beta.28` now contains this fix.

**Comment by tinchalamo** [comment]
I installed `1.0.0-beta.28` and the CraftQL Browser in the CP stopped working. I'm on Craft `3.0.27.1`.

**Comment by markhuot** [comment]
@tinchalamo, can you provide any error logs with this? One helpful way is to go to `/api/debug` and enter `{entries{id}}` in to the query field and see if you get a more informative error message (also, make sure `devMode` is on and your schema will be validated too).

**Comment by tinchalamo** [comment]
Looks like it's working again after update to Craft `3.0.29`.
