### ISSUE TITLE
"Not authorized" error when logged out in production

### ISSUE THREAD

**Issue by romainpoirier** [markhuot/craftql#58]
I'm having an error with CraftQL plugin in production: `"Not authorized"`.

I have created a token, and for the purpose of the test I have enabled all scopes' permissions.
In dev, I can ask the API whenever I'm logged or not. In production, this is working when I'm logged but not when I'm not.

Token, permissions and API path are the same in dev and prod.

I'm querying the API using JS like this:

```
// Post query
var xhr = new XMLHttpRequest();

xhr.responseType = 'json';
xhr.open('POST', '/api');

xhr.setRequestHeader('Authorization', 'bearer FTQxVq3vIDrE1x2-nkkSgAeKWoJIYrqrlGDtojRgYMFYm3vwJbpSkk19pd7eNEbL');
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.setRequestHeader('Accept', 'application/json');

// Print query
xhr.onload = function() {
	xhr.onload = function() {
		console.log(xhr.response);
		$timeout(function() {
			$scope[variable] = xhr.response.data.entries;
		}, 0);
	}
}

// Send query
xhr.send(JSON.stringify({query: query }));
```

Any idea what would going wrong? Do you think it is a bug?

**UPDATE 1:**
I finally found that prod server was removing the Authorization data from the sent Header.
Website and API are localized on the same server: this should not be a CORS issue.

In my JS file, I updated...
_This:_ `xhr.setRequestHeader('Authorization', 'bearer FTQxVq3vIDrE1x2-nkkSgAeKWoJIYrqrlGDtojRgYMFYm3vwJbpSkk19pd7eNEbL');`
_To this:_ `xhr.setRequestHeader('Token', 'bearer FTQxVq3vIDrE1x2-nkkSgAeKWoJIYrqrlGDtojRgYMFYm3vwJbpSkk19pd7eNEbL');`

And in `craftql/src/Controllers/ApiController.php`, I updated...
_This:_ `$authorization = Craft::$app->request->headers->get('authorization');`
_To this:_ `$authorization = Craft::$app->request->headers->get('token');`

This is now working as expected.

Any idea why Authorization data are not sent as Header in prod?

**UPDATE 2:**
I found that that Apache http Authorization header was disabled on prod server.
This line in htaccess solves the problem: `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`.

**Comment by romainpoirier** [comment]
**UPDATE:**
I finally found that prod server was removing the Authorization data from the sent Header.

In my JS file, I updated...
_This:_ `xhr.setRequestHeader('Authorization', 'bearer FTQxVq3vIDrE1x2-nkkSgAeKWoJIYrqrlGDtojRgYMFYm3vwJbpSkk19pd7eNEbL');`
_To this:_ `xhr.setRequestHeader('Token', 'bearer FTQxVq3vIDrE1x2-nkkSgAeKWoJIYrqrlGDtojRgYMFYm3vwJbpSkk19pd7eNEbL');`

And in `craftql/src/Controllers/ApiController.php`, I updated...
_This:_ `$authorization = Craft::$app->request->headers->get('authorization');`
_To this:_ `$authorization = Craft::$app->request->headers->get('token');`

Any idea why Authorization data are not sent as Header in prod?

**Comment by markhuot** [comment]
Yup, you found the culprit. This happens if you’re running PHP in CGI or FastCGI mode.

http://php.net/manual/en/features.http-auth.php#114877

Glad you got it working!!

**Comment by mdunbavan** [comment]
Hey I am still getting this error from my code below

```
const axios = require('axios');

const apiToken = 'M896UVAe90QFdGSrsLOF9MT__WULIs5iF1eHmEIwwgGXthHpuHFgruOkwG1k2vTf';
const apiUrl = 'http://sstudioapi.test';

const configureApi = axios.create({
  baseURL: apiUrl,
  header: {
    'authorisation': `bearer M896UVAe90QFdGSrsLOF9MT__WULIs5iF1eHmEIwwgGXthHpuHFgruOkwG1k2vTf`,
    'X-Requested-With': 'XMLHttpRequest',
    'Content-type':'application/json'
  }
});


module.exports = function (api) {
  api.loadSource(async store => {
    await configureApi.post('/api').then(response => {
      // returning the data here allows the caller to get it through another .then(...)
      console.log(JSON.stringify(response.data, 0, 2))
    })

    const contentType = store.addContentType({
      typeName: 'Projects'
    })

    //console.log(data['errors']);

    // for (const item of data) {
    //   contentType.addNode({
    //     id: item.id,
    //     title: item.title
    //   })
    // }

  })
}

```
