### ISSUE TITLE
Support for postDate

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#59]
Currently we have expiry date, date created and date modified. While it would be ideal to be able to edit any of these dates through a mutation, right now I'd love to be able to read post date off of an entry.

https://craftcms.com/docs/templating/entrymodel#postDate

**Comment by markhuot** [comment]
`dev-master` should fix this. I'll leave this open until a stable release is cut.

**Comment by markhuot** [comment]
`1.0.0-beta.28` now contains this fix.
