### ISSUE TITLE
Get extended user data and user photo

### ISSUE THREAD

**Issue by phoob** [markhuot/craftql#60]
Hello!

I'm tinkering with attaching fields to users. The goal is to create an employee registry. But CraftQL doesn't recognize the extra fields I've attached to users. What do you think about exposing these fields, as you do for entries?

Also, it would be great to be able to get the user photo url.. 

P

**Comment by markhuot** [comment]
Both of these should be possible on `dev-master` now. Please give it a test and let me know how it works and then I'll tag a stable release.

**Comment by phoob** [comment]
Works mostly. The extra fields are visible in GraphQL, and the photo as well. But the `uri` and `url` fields in the photo are `null` and if I query `folder` I get the error `"String cannot represent non scalar value: instance of craft\\models\\VolumeFolder"`

**Comment by markhuot** [comment]
Ah, so I think I'm a dummy. `uri` isn't a thing, I don't know where I got that from. I've removed `uri` from `dev-master`

URL will be `null` unless you adjust your Volume settings to enable "Assets in this volume have public URLs"

Re: folder, I'm not sure what that's supposed to return, but you should get a valid sub-selection now on `dev-master`.

**Comment by phoob** [comment]
Ah, ok! Works now! Thanks 💯

**Comment by markhuot** [comment]
Yay! This'll be included in the next stable release.

**Comment by phoob** [comment]
btw folder works now as well. Maybe because I set the public url option for the volume!?

**Comment by markhuot** [comment]
This is now included in `1.0.0-beta.29`.

**Comment by bzin** [comment]
@markhuot you should include this on the docs
_URL will be null unless you adjust your Volume settings to enable "Assets in this volume have public URLs"_ since it took I while to figure this out 📦

**Comment by markhuot** [comment]
Thanks @bzin, I'll definitely update the readme.

I'm curious, for volumes without public URLs would you expect a private `/admin` URL?

**Comment by bzin** [comment]
@markhuot I was not the one that set the Asset Volume, but I was working on a GraphQL query and wasn't able to immediately understand why this was not working.

And indeed you are probably right. We should not assume that the transformed image that is set if this does not have a public URL. So this little line in the README will help a lot, eheheh.

**Comment by andygott** [comment]
Thanks for making CraftQL, it’s made moving to a Craft/React setup super simple!

I’m struggling to find a way to get users’ photos via GraphQL. Comments on this issue seem to suggest that `{ users { photo } }` works, but when I try this in GraphiQL I get “Cannot query field ‘photo’ on type ‘user’.”

Is this possible? Any pointers would be really helpful.
