### ISSUE TITLE
Complete URL or URI for S3 volumes/assets

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#62]
Right now, any S3 asset will return `null` for URI or URL, even when it should have sufficient information to give a complete image URL. Populating a cloudfront id also doesnt seem to change anything. Are URI and URL only for locally hosted assets?

**Comment by markhuot** [comment]
Hrm, this should work. I don't usually use S3, though, because I shove everything behind Cloudflare and just cache everything to the moon. Let me test this locally and get back to you. There could be a bug that I need to work through.

For my clarification, how would you get the image URL in a traditional Craft template?

**Comment by askogrand** [comment]
@markhuot Im realizing that the assets arent public (we are using imgix as a cdn), so likely my real concern is that we cant inspect path on folder, which just gives us the local pathing on the volume.

When running this query:
```
eventPhotos {
    id
    folder
}
```
I get back:
```
{
  "error": "String cannot represent non scalar value: instance of craft\\models\\VolumeFolder"
}
```
And I cant define any properties on folder.

Without enabling public URLs, you obviously cant return full path, so my apologies on the misdirection of `URI` and `URL`.

**Comment by askogrand** [comment]
I would use the following to get the path on S3 in a template file
`{{ photo.folder.path }}{{ photo.filename() }}`

**Comment by askogrand** [comment]
Considering this is now an issue with folder being inaccessible and not whats in the description, Ill close the ticket.

**Comment by markhuot** [comment]
FYI, after #60 you should be able to get `photo { folder { path` out of CraftQL now. If you're curious to try it again, let me know if you have any issues.

Feel free to re-open if you're still having issues.
