### ISSUE TITLE
[Enhancement] Super Table Support

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#63]
Wanted to see what your thoughts are in adding support for [Super Table](https://github.com/verbb/super-table) now that it's available for Craft 3.

I had reached out before release and they mentioned that it was something that they would be open to a PR, but weren't sure about implementation / maintaining due to their knowledge of GraphQL.

**Comment by markhuot** [comment]
Phew, this would be inception inside inception but definitely possible. I'll take a look at adding in support within this Repo. If Verbb folk want to take the code in to their repo at some point in the future that'd be fine too.

**Comment by markhuot** [comment]
`dev-master` adds support for Super Table. It's experimental so let me know how it goes.

**Comment by markhuot** [comment]
This is now included in `1.0.0-beta.29`.
