### ISSUE TITLE
Lightswitch or boolean field creates sql error when value is FALSE

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#65]
Any custom field that is boolean or lightswitch will

1) Return the correct value in the query response
2) Return the correct entries when fed a value of true in the query parameters

However, if you are searching for entries where the field value is false, the sql will error as it expects a boolean to be printed out, but nothing is there:

`
"error": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type boolean: \"\"\nThe SQL being executed was: SELECT \"elements\".\"id\", \"elements\".\"fieldLayoutId\", \"elements\".\"uid\", \"elements\".\"enabled\", \"elements\".\"archived\", \"elements\".\"dateCreated\", \"elements\".\"dateUpdated\", \"elements_sites\".\"slug\", \"elements_sites\".\"uri\", \"elements_sites\".\"enabled\" AS \"enabledForSite\", \"entries\".\"sectionId\", \"entries\".\"typeId\", \"entries\".\"authorId\", \"entries\".\"postDate\", \"entries\".\"expiryDate\", \"content\".\"id\" AS \"contentId\", \"content\".\"title\", \"content\".\"field_trueflag\", \"structureelements\".\"root\", \"structureelements\".\"lft\", \"structureelements\".\"rgt\", \"structureelements\".\"level\", \"structureelements\".\"structureId\"\nFROM (SELECT \"elements\".\"id\" AS \"elementsId\", \"elements_sites\".\"id\" AS \"elementsSitesId\", \"content\".\"id\" AS \"contentId\"\nFROM \"elements\" \"elements\"\nINNER JOIN \"entries\" \"entries\" ON \"entries\".\"id\" = \"elements\".\"id\"\nINNER JOIN \"elements_sites\" \"elements_sites\" ON \"elements_sites\".\"elementId\" = \"elements\".\"id\"\nINNER JOIN \"content\" \"content\" ON \"content\".\"elementId\" = \"elements\".\"id\"\nLEFT JOIN \"structureelements\" \"structureelements\" ON \"structureelements\".\"elementId\" = \"elements\".\"id\"\nWHERE (\"entries\".\"typeId\" = '1') AND (\"entries\".\"sectionId\" = '1') AND (\"elements_sites\".\"siteId\"=1) AND (\"content\".\"siteId\"=1) AND (\"content\".\"field_trueflag\" = '') AND (\"elements\".\"archived\"=FALSE) AND (((\"elements\".\"enabled\"=TRUE) AND (\"elements_sites\".\"enabled\"=TRUE)) AND (\"entries\".\"postDate\" <= '2018-02-21 06:14:36') AND ((\"entries\".\"expiryDate\" IS NULL) OR (\"entries\".\"expiryDate\" > '2018-02-21 06:14:36'))) AND (\"elements_sites\".\"enabled\"=TRUE)\nORDER BY \"entries\".\"postDate\" DESC) \"subquery\"\nINNER JOIN \"entries\" \"entries\" ON \"entries\".\"id\" = \"subquery\".\"elementsId\"\nINNER JOIN \"elements\" \"elements\" ON \"elements\".\"id\" = \"subquery\".\"elementsId\"\nINNER JOIN \"elements_sites\" \"elements_sites\" ON \"elements_sites\".\"id\" = \"subquery\".\"elementsSitesId\"\nINNER JOIN \"content\" \"content\" ON \"content\".\"id\" = \"subquery\".\"contentId\"\nLEFT JOIN \"structureelements\" \"structureelements\" ON \"structureelements\".\"elementId\" = \"subquery\".\"elementsId\"\nORDER BY \"entries\".\"postDate\" DESC"
`

Graphql Query:
`
query {
  entries(trueflag: false) {
    id
    title
    ...on Products {
      trueflag
    }
  }
}
`

**Comment by markhuot** [comment]
This exact query worked for me on RC13. Would you be able try an update and see if that helps? If it doesn't, would you be able to send me an export of your DB so I can try to run it myself?

**Comment by askogrand** [comment]
On RC-13, Im getting the same result. Curious if its a postgres issue. Sent DB your way.

**Comment by markhuot** [comment]
Looks like it could be a Postgres issue. I added the following in to a test template using Postgres,

```
{{ craft.entries.aLightSwitchField(false).count() }}
```

That gave me the same error that CraftQL is giving me. Would you be able to open this as a bug on the [craftcms/cms](https://github.com/craftcms/cms) repo and see what the P&T folk think?

**Comment by askogrand** [comment]
@markhuot Done: https://github.com/craftcms/cms/issues/2530#issuecomment-370551899

**Comment by markhuot** [comment]
And fixed with https://github.com/craftcms/cms/commit/6c2381c971b4faf12bd153175c80b6bf0462ad14 already! I'm going to close this issue, but please re-open if you're still having issues after updating tomorrow.
