### ISSUE TITLE
New matrix blocks in drafts gets id = null

### ISSUE THREAD

**Issue by phoob** [markhuot/craftql#66]
TL;DR:

If you create a draft with multiple new matrix fields, they get string ids in the form `new` + `increment`, ie. `new1`, `new2`, ...  In CraftQL this leads to these fields getting a `null` id, presumably because it expects an INT.

See discussion here: https://github.com/markhuot/craftql/commit/e976f422510b0c6c2828e0db5b4be683357876a7

**Comment by markhuot** [comment]
`dev-master` switches this to a `String` field to account for drafts. It's gross, but probably the best way to do it long term.

**Comment by markhuot** [comment]
This was released with 1.0.0
