### ISSUE TITLE
RC-12 breaks search parameter on entries/entriesConnection

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#69]
`query SearchPageQuery {
  entriesConnection(
    search: "Parkland"
  ) {
    totalCount
    results: entries {
      id
      title
      slug
    }
  }
}
`

Worked perfectly well on RC-11. RC-12 now throws this SQL error:

`{
  "error": "SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"elements.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 15: ORDER BY CASE WHEN \"elements\".\"id\"=4530 THEN 0 WHEN \"element...\n                            ^\nThe SQL being executed was: SELECT COUNT(*)\nFROM (SELECT \"elements\".\"id\" AS \"elementsId\", \"elements_sites\".\"id\" AS \"elementsSitesId\", \"content\".\"id\" AS \"contentId\"\nFROM \"elements\" \"elements\"\nINNER JOIN \"entries\" \"entries\" ON \"entries\".\"id\" = \"elements\".\"id\"\nINNER JOIN \"elements_sites\" \"elements_sites\" ON \"elements_sites\".\"elementId\" = \"elements\".\"id\"\nINNER JOIN \"content\" \"content\" ON \"content\".\"elementId\" = \"elements\".\"id\"\nLEFT JOIN \"structureelements\" \"structureelements\" ON \"structureelements\".\"elementId\" = \"elements\".\"id\"\nWHERE ((\"entries\".\"typeId\" = '16') OR (\"entries\".\"typeId\" = '6') OR (\"entries\".\"typeId\" = '4') OR (\"entries\".\"typeId\" = '15') OR (\"entries\".\"typeId\" = '12') OR (\"entries\".\"typeId\" = '10') OR (\"entries\".\"typeId\" = '9') OR (\"entries\".\"typeId\" = '5') OR (\"entries\".\"typeId\" = '8') OR (\"entries\".\"typeId\" = '7') OR (\"entries\".\"typeId\" = '3') OR (\"entries\".\"typeId\" = '11') OR (\"entries\".\"typeId\" = '2')) AND ((\"entries\".\"sectionId\" = '15') OR (\"entries\".\"sectionId\" = '6') OR (\"entries\".\"sectionId\" = '4') OR (\"entries\".\"sectionId\" = '14') OR (\"entries\".\"sectionId\" = '12') OR (\"entries\".\"sectionId\" = '10') OR (\"entries\".\"sectionId\" = '9') OR (\"entries\".\"sectionId\" = '5') OR (\"entries\".\"sectionId\" = '8') OR (\"entries\".\"sectionId\" = '7') OR (\"entries\".\"sectionId\" = '3') OR (\"entries\".\"sectionId\" = '11') OR (\"entries\".\"sectionId\" = '2')) AND (\"elements_sites\".\"siteId\"=1) AND (\"content\".\"siteId\"=1) AND (\"elements\".\"archived\"=FALSE) AND (((\"elements\".\"enabled\"=TRUE) AND (\"elements_sites\".\"enabled\"=TRUE)) AND (\"entries\".\"postDate\" <= '2018-02-27 15:49:16') AND ((\"entries\".\"expiryDate\" IS NULL) OR (\"entries\".\"expiryDate\" > '2018-02-27 15:49:16'))) AND (\"elements_sites\".\"enabled\"=TRUE) AND (\"elements\".\"id\" IN (4530, 4086, 122))\nORDER BY CASE WHEN \"elements\".\"id\"=4530 THEN 0 WHEN \"elements\".\"id\"=4086 THEN 1 WHEN \"elements\".\"id\"=122 THEN 2 ELSE 3 END) \"subquery\"\nINNER JOIN \"entries\" \"entries\" ON \"entries\".\"id\" = \"subquery\".\"elementsId\"\nINNER JOIN \"elements\" \"elements\" ON \"elements\".\"id\" = \"subquery\".\"elementsId\"\nINNER JOIN \"elements_sites\" \"elements_sites\" ON \"elements_sites\".\"id\" = \"subquery\".\"elementsSitesId\"\nINNER JOIN \"content\" \"content\" ON \"content\".\"id\" = \"subquery\".\"contentId\"\nLEFT JOIN \"structureelements\" \"structureelements\" ON \"structureelements\".\"elementId\" = \"subquery\".\"elementsId\"\nORDER BY CASE WHEN \"elements\".\"id\"=4530 THEN 0 WHEN \"elements\".\"id\"=4086 THEN 1 WHEN \"elements\".\"id\"=122 THEN 2 ELSE 3 END"
}`

**Comment by markhuot** [comment]
Did you update SQL as well? This is an error that usually comes around with an update to MySQL.

Alternatively, this could be a bug in RC-12. I'll dig deeper.

**Comment by askogrand** [comment]
Our deployed version was RC-12, and this query was broken. My local environment was RC-11, and it worked. I simply ran `composer update`, and updated RC-11 to 12 locally, after which I started to receive the error. Its possible something else is causing the issue, but did not upgrade my db. Im running Postgres and not MySQL.

**Comment by markhuot** [comment]
Ah, got it, there's a similar issue here: https://github.com/craftcms/cms/issues/2352.

It could have to do with how I'm setting the "order" parameter.

**Comment by keithmancuso** [comment]
May not be related but I had to downgrade from RC-12 back to 10 because some of my queries seemed to hit an infinite loop on RC-12 and would crash the database.

I wasn’t able to dig too deeply into what caused it, but when I downgraded it went back to loading fine.  Heres the query I was using if thats helpful.  Is just getting a single entry for the homepage

‘’’
{
  entry(slug: "homepage") {
    title
    url
    ... on Homepage {
      headline
      subheadline
      featuredCaseStudies {
        ... on CaseStudiesCaseStudy {
          id
          title
          subTitle
          uri
          imageGridBrowserChrome
          mainGridImage {
            url
          }
          imageGrid {
            ... on ImageGridAdditionalImage {
              image {
                url
              }
              position
            }
          }
        }
      }
    }
  }
}
‘’’

**Comment by markhuot** [comment]
Gents, can you check if RC13 fixes these issues?

**Comment by askogrand** [comment]
Still experiencing the same issue on RC13.

**Comment by markhuot** [comment]
@askogrand, you seem to have found another bug in Craft, itself. Using Postgres (may not happen in MySQL), I got the same error with the following template,

```handlebars
{{ craft.entries.search('Parkland').count() }}
```

Would you be able to open this as a ticket against [craftcms/cms](https://github.com/craftcms/cms/issues)? Sorry I couldn't debug it further :(

I'm going to close this in favor of the core bug. @keithmancuso, let me know in a new ticket if you're still having issue with RC13.

**Comment by askogrand** [comment]
@markhuot Thanks — Ill make it part of my checklist to actual try the template code before filing a ticket. Thanks for figuring that out. Ill follow up with craft directly.

**Comment by markhuot** [comment]
Thanks. And no worries about the CraftQL ticket. I started debugging this in CraftQL because I assumed the error was there too. I'm surprised by these Craft/Postgres issues.
