### ISSUE TITLE
Post install issue

### ISSUE THREAD

**Issue by StevenLangbroek** [markhuot/craftql#7]
So I just installed through composer (running Craft on homestead), and when I go to the GraphiQL interface, the API requests give me 400 errors:

```
HTTP 400 – Bad Request – yii\web\BadRequestHttpException

Unable to verify your data submission.
```

I thought I might need to generate a token, so I clicked the "Generate token button", which gave me this error:
<img width="1677" alt="craft-exception" src="https://user-images.githubusercontent.com/296796/29525931-7f671546-8694-11e7-98dd-2094f153c426.png">

Did I miss something here?

**Comment by StevenLangbroek** [comment]
So I uninstalled, changed `Install.php` L19 to:

```php
'isWritable' => $this->boolean()->notNull()->defaultValue(true),
```

Which allows me to create keys, but it doesn't solve the problem (still `400` in GraphiQL), and when I click on a token's settings, I get this error:

<img width="1677" alt="craft-scopese" src="https://user-images.githubusercontent.com/296796/29527025-ce74def4-8697-11e7-8157-15263b54158c.png">

**Comment by StevenLangbroek** [comment]
I'm on beta24, php 7.1.7 btw.

**Comment by markhuot** [comment]
Hum, there shouldn't be an `isWritable` any more. That was an old release. Let me make sure my Packagist tag is updated.

**Comment by markhuot** [comment]
Ah, my bad. I didn't understand how Yii's migrations work. Install doesn't include the migration, like I thought it did. I just posted some install fixes here,

https://github.com/markhuot/craftql/commit/56325407c6a85ae3f9d2b7ebac49d6148a7045e1

If you're pulling off Packagist, make sure you get `1.0.0-beta.3`

**Comment by markhuot** [comment]
Oh, you'll probably need to uninstall and re-install the plugin to get it to work.

**Comment by markhuot** [comment]
Note, `1.0.0-beta.4` is updated to fix a `csrf` issue with `beta.3`.

**Comment by StevenLangbroek** [comment]
Works like a charm! Thanks!

**Comment by narration-sd** [comment]
@markhuot could this have had a regression?  As you'll see from other note, I'm getting this on a fresh install of Craft 3.1.30 with normative CraftQL 1.3.2 off the plugin store -- a validity testing site for my own plugin, but  it's not in there -- only Redactor and ElementApi.
