### ISSUE TITLE
Support for sub fields on users field type

### ISSUE THREAD

**Issue by keithmancuso** [markhuot/craftql#70]
Seems like currently you can access subfields from selected entries from and entries field but users fields seem to just return a string instead of a object with all the user custom fields?

**Comment by cjgrauco** [comment]
Any news regarding this issue? Having the same problem.

**Comment by askogrand** [comment]
@keithmancuso Do you have an example query of what you'd like to do?

**Comment by cjgrauco** [comment]
I can add an example:

In my project i have a channel with a field containing users, like this:
http://prntscr.com/imzs2v

If i try to get data(id, slug etc.) from the user through the channel i get this message:
http://prntscr.com/imzs2

And if i query for supervisor without a sub-selection i get the following error message:
{
  "error": "String cannot represent non scalar value: instance of craft\\elements\\db\\UserQuery"
}


It would be very convenient to access user-fields through the channel query.
My experience with graphQL is limited so i might have missed something trivial, if that is the case how would you set up a query to get data from the user through the channel query? 

Thanks in advance, and loving the plugin!

**Comment by markhuot** [comment]
This should now be possible on `dev-master`. Access is through custom fields, same as an `entries` field. Let me know if you have any issues.

**Comment by keithmancuso** [comment]
Tested this and its working!  Thanks @markhuot!

**Comment by markhuot** [comment]
This was released with 1.0.0
