### ISSUE TITLE
Request: Add default cache headers

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#72]
https://github.com/ostark/upper

There are a few other plugins that will set/reset http response cache headers. We'd love to be able to use them, but at the moment, the only header I see getting set is ContentType. Would be nice to be able to get the same behavior for setting cache as we would get on regular template rendering.

**Comment by markhuot** [comment]
I'm not sure how you could do this, though, with GraphQL. Since everything is through a single `/api` endpoint you can't edge cache as cleanly…

How would you envision caching working? Based on the query? Based on the fields returned?

**Comment by askogrand** [comment]
I think that caching would only be available via the `GET` method, and would be URL based.

**Comment by hansef** [comment]
Correct, we're going to use the (non-standard, but spec-supported) GET request form and these are non-user-specific queries, so caching based on URL (which will include both the query and the variables) should work ok here.

Upper sets a couple of headers (cache-control, and a service-specific cache header, e.g. Surrogate-Key for fastly).

The challenge is that this seems to happen attached to EVENT_AFTER_RENDER_PAGE_TEMPLATE (https://github.com/ostark/upper/blob/master/src/EventRegistrar.php#L86) which I'm guessing CraftQL doesn't run through?

**Comment by markhuot** [comment]
Hrm, okay, I see. I think I can get support for this some how. I don't want this to become "standard" because I'd like CraftQL to stick to the standard, out of the box. However, maybe a configuration event or something like that would provide a good way to adjust this. Let me think on this for a day.

**Comment by markhuot** [comment]
@askogrand and @hansef, here's what I'm thinking. You can already add headers to `config/craftql.php`. You would do so like so,

```php
return [
    'headers' => [
        'cache-control' => 'max-age=600',
    ],
];
```

On `dev-master` the value of the header can now be a callback, so you could do,

```php
return [
    'headers' => [
        'cache-control' => 'max-age=600',
        'cache-tag' => function ($schema, $input, $variables, $result) {
            return md5($input.json_encode($variables));
        },
    ],
];
```

☝️ this would give you a unique tag for every combination of input/variables. If the variables change or the query changes you'd end up with a new tag.

Let me know if this helps.

**Comment by markhuot** [comment]
This was pushed with 1.0.0
