### ISSUE TITLE
[Enhancement]: Support for Typed Link Field

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#75]
Wanted to throw this field type into the ring for a schema addition [Typed Link Field](https://github.com/sebastian-lenz/craft-linkfield)

**Comment by sebastian-lenz** [comment]
The next release of the typed link field will include experimental support for CraftQL, see https://github.com/sebastian-lenz/craft-linkfield/issues/20.

However, I'm not familiar with GraphQL, so if anyone with a deeper understanding would like to pick up this topic, any contributions would be welcome.

**Comment by markhuot** [comment]
Looks like this merged? I'm going to close this. Feel free to re-open if you'd like help with this.
