### ISSUE TITLE
Query by custom fields on Categories and Users and single category query fields

### ISSUE THREAD

**Issue by keithmancuso** [markhuot/craftql#76]
Seems like right now you only have custom field filtering support on `entries` but not on `categories` or `users`.

Similarly would love to see an option for single `category` and `user` similar to the `entry` for grabbing a single category and user.

I assume these things are already on your radar but just wanted to log it.

**Comment by markhuot** [comment]
`dev-master` should have all of this implemented now. You'll see new `category` and `user` fields as well as custom field searches on them. Note, `search:"title:foo"` should have worked too before this change, as a fall back if you're not able to upgrade immediately.

**Comment by keithmancuso** [comment]
Wow, amazing!  Will give it a shot tomorrow and let you know

**Comment by markhuot** [comment]
This is released with 1.0.0
