### ISSUE TITLE
Accessing globals for specific site

### ISSUE THREAD

**Issue by edolyne** [markhuot/craftql#77]
When querying globals you're currently not able to query them based on a specific site.

**Comment by markhuot** [comment]
How would you do this in a native template? Or, I guess you wouldn't have to because `globalVar` would already be specific to the site that Craft loaded the template for?

**Comment by edolyne** [comment]
I think that's the main difference is that within the template it would already be site aware and serve the content for that site. I'd suggest using a format similar to `entries` where we can pass either a `site` or `siteId` to pull the appropriate content.

**Comment by markhuot** [comment]
`dev-master` should support both the `site:"handle"` and `siteId:1` arguments on the `globals` field now. You can use it like so,

```graphql
{
  globals(site:"anotherSite") {
    globalSet {
      globalField
    }
  }
}
```

**Comment by edolyne** [comment]
![](https://media.giphy.com/media/5wWf7GW1AzV6pF3MaVW/giphy.gif)

**Comment by markhuot** [comment]
FYI, there's going to be a breaking changing coming on `dev-master`. I'm going to move the `site:` argument over to an enum so we get autocomplete in GraphiQL.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix. Note, I did not implement the enum on the `site:` argument yet. Maybe for 2.0…?
