### ISSUE TITLE
[Enhancement]: Support for Videos 2

### ISSUE THREAD

**Issue by tinchalamo** [markhuot/craftql#79]
Another field type for a schema addition [Videos 2](https://github.com/dukt/videos-docs)

**Comment by markhuot** [comment]
`dev-master` now has support for Videos. Please let me know if you have any issues with it.

**Comment by markhuot** [comment]
Re-opening until this gets a stable tag.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
