### ISSUE TITLE
Dates in ISO 8601 Date Format

### ISSUE THREAD

**Issue by tinchalamo** [markhuot/craftql#81]
Is there any way to convert dates to ISO 8601 date format? I'm trying to use the `@date` directive to convert it as `Y-m-dTH:i:sZ`, but the `T` is converted into a timezone and `Z` is converting into a timezone offset when it should render as `2018-03-28T19:04:55Z`.

**Comment by markhuot** [comment]
Try escaping the raw characters, `Y-m-d\TH:i:s\Z`.

It _should_ be the same syntax you’d pass to php.net/date

Let me know how it works.

**Comment by tinchalamo** [comment]
Here's what I tried:

`@date(as:"Y-m-d\TH:i:s\Z")`

But I get this syntax error:

`
{
  "errors": [
    {
      "message": "Syntax Error GraphQL (24:37) Invalid character escape sequence: \\T\n\n23:           id\n24:           startTime @date(as:\"Y-m-d\\TH:i:s\\Z\")\n                                        ^\n25:           endTime @date(as:\"Y-m-dTH:i:s\")\n",
      "category": "graphql",
      "locations": [
        {
          "line": 24,
          "column": 37
        }
      ]
    }
  ]
}
`

**Comment by markhuot** [comment]
`dev-master` now contains the `format` argument on the `@date` directive. That means you can do the following to get an ISO-8601 date,

```graphql
{
  entries {
    dateCreated @date(format: iso8601)
  }
}
```

**Comment by markhuot** [comment]
This was released with 1.0.0

**Comment by seidtgeist** [comment]
@markhuot Is there any chance we can change the default date format to be ISO8601 in a semver major release?
