### ISSUE TITLE
Support for "not" operators  in queries  

### ISSUE THREAD

**Issue by keithmancuso** [markhuot/craftql#82]
I realize this might be a bit of a tall order considering the strongly typed arguments in graphQl but I wanted to mention it because its come up for us a few times over the last few weeks.

Basically what we are looking to do is get a list of things like blog posts but exclude a blog post by slug or Id. This is a pretty common pattern for us when we are doing things like pulling up other blog posts on a single blog post detail page, but I cant figure out anyway to do with currently with CraftQl?

In twig would be {Id: 'not 123"} but since Id is an Int theres no way to do that and  ! operator doesnt seem to work either..

hmmm

**Comment by markhuot** [comment]
Good point. Definitely a common use pattern too. I’ll look at this. What I’ll probably support is,

```graphql
{
  entries(idNot: [123,456]) {
    is
  }
}
```

**Comment by markhuot** [comment]
`dev-master` now contains this functionality. `idNot:` will accept the same array of IDs as `id:` but during the resolve it'll automatically add `not: {$passedIds}` to the query.

**Comment by markhuot** [comment]
This was released with 1.0.0
