### ISSUE TITLE
Support array of IDs for CategoryConnection

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#83]
Entries can take `[Int]`, but for categories, and categories connection, we can only provide a single ID. While I can sometimes work around a common ancestor, or level, sometimes it would be nice to feed in an array of IDs. While a single id is the default behavior in twig/craft, it can take an array, like so:

`craft.categories.id([11, 109])`

**Comment by markhuot** [comment]
`dev-master` now allows for this.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
