### ISSUE TITLE
[Bug]: Cannot return null for non-nullable field SectionSiteSettings.uriFormat

### ISSUE THREAD

**Issue by stigzelm** [markhuot/craftql#90]
Found a bug when trying to access the sections siteSettings uriFormat.

If all off my sections have urls, this works.
If I decide that one of my sections in craft should not have urls, this error appears:
"error": "Cannot return null for non-nullable field SectionSiteSettings.uriFormat."

Or is there a way to query (in graphQL) data conditionally based on another fields value. Example:
if hasUrls is true, then show return uriFormat.

**Comment by markhuot** [comment]
I think it's safer to just remove `nonNull` from `uriFormat`. This is fixed on `dev-master`.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
