### ISSUE TITLE
Third party object fields not working

### ISSUE THREAD

**Issue by jordihendrix** [markhuot/craftql#91]
The docs mention using `markhuot\CraftQL\Builders\Schema->addObjectField` to add a custom object field type to graphQL (in the "Third-pary Field Support" section). This function appears to be nonexistent, so there seems to be no way to add an object type field to the schema at this moment.

**Comment by markhuot** [comment]
Thanks, that should be fixed. It's actually `Schema::addField($object)->type($type)`. You can see the updated example here,

https://github.com/markhuot/craftql/blob/master/README.md#third-pary-field-support

**Comment by markhuot** [comment]
Okay, thanks. If there's some code you can share I'm happy to take a peek.

**Comment by markhuot** [comment]
I'm going to close this. If you're still having issues with it please open a PR or let me know where I can take a look and I'd be happy to dig in deeper.
