### ISSUE TITLE
[FEATURE] Ability to get disabled entries for a dev/staging

### ISSUE THREAD

**Issue by stursby** [markhuot/craftql#92]
Hey @markhuot, so would it be possible to get ALL entries, even if they are disabled in a dev/staging environment? I'm running Craft headless w/ Nuxt and would love to be able to "preview" WIP entries but so far it looks like I can only get "enabled" entries.

Would be great if this was an option in the Token Scopes, to allow "all entries" no matter what their status.

OR, if there's a way around this currently, any ideas would be much appreciated! Thanks.

**Comment by markhuot** [comment]
CraftQL just proxies to `craft.entries` so the same logic there should apply here. For example,

```graphql
{
  entries {
    id
  }
}
```

That'll just return `live` entries. If you want to return disabled entries you need `status:"disabled"`.

```graphql
{
  entries(status:"disabled") {
    id
  }
}
```

But that'll only return disabled entries. If you want _all_ entries you need `null` per: [https://docs.craftcms.com/…](https://docs.craftcms.com/v2/templating/craft.entries.html#status)

```graphql
{
  entries(status: null) {
    id
  }
}
```

Let me know if you have any issues with this or it doesn't work how you would expect.

**Comment by stursby** [comment]
@markhuot Perfect, thanks very much!

**Comment by seidtgeist** [comment]
@markhuot Might it make sense to have a per-query setting for the default status of entries, related entries and other queries?

It would be the difference between adding at least one `status` field to every query of every page (which would potentially be a lot of work), and having a different preview endpoint, or a query string parameter for setting the default status (effectively creating a preview API for free).

**Comment by narration-sd** [comment]
Sounds like a directive, doesn't it?  Fun to write...

**Comment by seidtgeist** [comment]
Ohey @narration-sd! I realize I never got back to your email, sorry about that. I just got around to working on the preview side of things yesterday, and I‘ll have a closer look with @pauloelias soon!

**Comment by narration-sd** [comment]
A smile. I looked you up, so not having surprises ;). A few days more will just get you something nice, I promise, so not a rush. Let's speak later, all right? Mark will be having kittens for this off-topic. Maybe there's an idea here for him, anyway.

**Comment by narration-sd** [comment]
p.s.  Live previews are fine; the nice thing is about a huge acceleration in setting them up. I think you'll appreciate it.
