### ISSUE TITLE
[Enhancement] New JavaScript package (`craftql-bindings`?) using `graphql-bindings`

### ISSUE THREAD

**Issue by jgeschwendt** [markhuot/craftql#95]
Just an idea! This plugin reminds me very much of the Prisma GraphQL service (auto-generated schema). A package like this would allow for more customization on another API server, as well as Type-Checking for Typescript/Flow users.

**Comment by markhuot** [comment]
This makes sense and goes hand in hand with some work I've been doing to autogenerate Apollo bindings for their Heuristic Fragment Parser.

What are you looking for at the end though…

>Type-Checking for Typescript/Flow users.

Some binding file that CraftQL could generate that TS could read?

**Comment by markhuot** [comment]
Could you use `apollo-codegen` for this?  I've used it with Swift before and it generates really nice type files. You just set `--target typescript`, for example: https://github.com/apollographql/apollo-codegen

I'll look at what it would take to do this _in_ CraftQL itself. I suppose I could add Node dependancies to CraftQL, but there aren't any yet and I'd like to avoid them, if I can.

----

Related, the `.graphql` file would be really neat coming out of CraftQL. Let me also look in to what it would take to make that happen.

**Comment by markhuot** [comment]
The second half was easier than I thought. If you update to `dev-master` via Composer you can now,

```bash
$ ./craft craftql/tools/print-schema > ./schema.graphql
```

That'll give you a schema that you can use however you need. 

I'm still looking in to the first half which will be a bit more complex.

**Comment by jgeschwendt** [comment]
This has fallen outside of the scope of our craft projects and the tooling around the idea has changed quite a bit. If the need arises I’ll get something working and report it back here.

**Comment by markhuot** [comment]
Thanks for the update @jgeschwendt.
