### ISSUE TITLE
Element type support for entriesConnection/relatedEntries

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#98]
The `entriesConnection/relatedEntries` stuff seems pretty focussed on entries. Is there a reason it is limited to Entries and not Categories, Assets, etc.?

Basically trying to do your connection example, but with the target relationship being a Category: https://github.com/markhuot/craftql#relationships (`relatedCategories` or `relatedElements`?)

**Comment by markhuot** [comment]
Ah, this makes good sense. I don't believe the functionality is implemented yet, not for any reason other than I hadn't gotten to it. I'll work on this soon, though, and let you know when it's implemented.

**Comment by timkelty** [comment]
Cool - I'll make a separate issue for doing the reverse…either I'm doing something wrong or there a bug :)

**Comment by markhuot** [comment]
I've added support for `relatedCategories` on an `EntryEdge` within the `dev-master` branch. Please test it out if you're able to.

I'm looking at `relatedElements`, but with the strict type system that would involve a new interface so I'm weighing the benefit of it.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
