### ISSUE TITLE
categoriesConnection/relatedEntries not returning results

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#99]
Probably most easily illustrated with this screenshot:

![screen_shot_2018-05-25_at_11_05_51_am](https://user-images.githubusercontent.com/18329/40551956-5995678a-600c-11e8-9fc8-9b4113fc5eff.png)

Am I doing something wrong, or should this be returning relatedEntries?

**Comment by timkelty** [comment]
Figured it out…the related entries were in a different site!

So I had to do:

```
{
  categoriesConnection(id: 50) {
    totalCount
    edges {
      node {
        title   # the category title
      }
      relatedEntries(siteId: 2) {
        entries {
          title # an entry title, that's related to this category
        }
      }
    }
  }
}
```

**Comment by markhuot** [comment]
I'm looking at `relatedCategories` over in #98.

Is any part of this still a bug? It seems like crossing sites would require `siteId:`. Don't the twig templates currently require `site()` too?

**Comment by timkelty** [comment]
Yep twig would require `site`/`siteId` if querying a different site. So I think we're all set here!
